### ISSUE TITLE
Add support for checking anonymous against ACL

### ISSUE THREAD

**Issue by perlausten** [OpenNTF/org.openntf.xsp.jakartaee#105]
If anonymous have No Access in ACL then respond with 401/NoAccessSignal.

**Comment by jesse-gallagher** [comment]
Hmm, I think it behaves like this currently by virtue of Domino's built-in login page check. I'll double-check on that, though.

**Comment by perlausten** [comment]
I can confirm that prompt for authentication for anonymous with no access in ACL now works without using @RolesAllowed(“login”).

**Comment by perlausten** [comment]
After fetching latest commits I now get a stack trace returned instead of an authentication prompt:

```
{
    "message": "org.openntf.domino.exceptions.OpenNTFNotesException: Notes error: You are not authorized to perform that operation",
    "stackTrace": [
        [
            "org.openntf.domino.exceptions.OpenNTFNotesException: null",
            "  at org.openntf.domino.utils.DominoUtils.handleException(DominoUtils.java:428)",
            "  at org.openntf.domino.utils.DominoUtils.handleException(DominoUtils.java:410)",
            "  at org.openntf.domino.impl.NoteCollection.buildCollection(NoteCollection.java:214)",
            "  at dk.fmcgsolutions.utils.FmcgUtils.getVersionNumber(FmcgUtils.java:230)",
            "  at dk.fmcgsolutions.utils.FmcgUtils.getBuildVersion(FmcgUtils.java:223)",
            "  at dk.fmcgsolutions.service.API.version(API.java:80)",
            "  at org.jboss.weld.generated.proxies.default.API$Proxy$_$$_WeldClientProxy.version(Unknown Source)",
            "  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
            "  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
            "  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
            "  at java.lang.reflect.Method.invoke(Method.java:498)",
            "  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)",
            "  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$162/0x0000000000000000.get(Unknown Source)",
            "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$160/0x0000000000000000.run(Unknown Source)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$161/0x0000000000000000.get(Unknown Source)",
            "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)",
            "  at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)",
            "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.service(FacesJAXRSServletContainer.java:140)",
            "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
            "  at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:65)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:76)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:1)",
            "  at com.mindoo.domino.jna.gc.NotesGC$3.run(NotesGC.java:511)",
            "  at java.security.AccessController.doPrivileged(AccessController.java:682)",
            "  at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:506)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService.doService(DominoJNAHttpService.java:68)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)",
            "  at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)"
        ],
        [
            "lotus.domino.NotesException: Notes error: You are not authorized to perform that operation",
            "  at lotus.domino.local.NoteCollection.buildCollection(Unknown Source)",
            "  at org.openntf.domino.impl.NoteCollection.buildCollection(NoteCollection.java:211)",
            "  at dk.fmcgsolutions.utils.FmcgUtils.getVersionNumber(FmcgUtils.java:230)",
            "  at dk.fmcgsolutions.utils.FmcgUtils.getBuildVersion(FmcgUtils.java:223)",
            "  at dk.fmcgsolutions.service.API.version(API.java:80)",
            "  at org.jboss.weld.generated.proxies.default.API$Proxy$_$$_WeldClientProxy.version(Unknown Source)",
            "  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
            "  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
            "  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
            "  at java.lang.reflect.Method.invoke(Method.java:498)",
            "  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)",
            "  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$162/0x0000000000000000.get(Unknown Source)",
            "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$160/0x0000000000000000.run(Unknown Source)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$161/0x0000000000000000.get(Unknown Source)",
            "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)",
            "  at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)",
            "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.service(FacesJAXRSServletContainer.java:140)",
            "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
            "  at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:65)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:76)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:1)",
            "  at com.mindoo.domino.jna.gc.NotesGC$3.run(NotesGC.java:511)",
            "  at java.security.AccessController.doPrivileged(AccessController.java:682)",
            "  at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:506)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService.doService(DominoJNAHttpService.java:68)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)",
            "  at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)"
        ]
    ]
}
```

**Comment by jesse-gallagher** [comment]
Hmm, so the user has outright No Access in the ACL of the DB with the service, but it’s still trying to execute the service? That’s odd… I’ll have to see if I can reproduce that.

**Comment by perlausten** [comment]
The user (anonymous) has "Read public documents" and No Access.

**Comment by jesse-gallagher** [comment]
Ahh, that’ll be a tricky one, then. In theory, I don’t want to block all access to the app in that situation, and trapping for “you are not authorized” as a Notes exception has its own trouble ( https://github.com/OpenNTF/org.openntf.xsp.jakartaee/issues/100 ). I’ll ponder it, though.

**Comment by perlausten** [comment]
I have changed my mind and only see this as nice to have but not essential at all. 

A proper REST API needs anonymous/un-authenticated access for OPTIONS requests in order to handle preflight requests for CORS while at the same time offering authenticated GET/POST requests. The current solution with @RolesAllowed(“login”) handles this.
