### ISSUE TITLE
MP Config CDI bindings prevent app from loading after design change

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#114]
This happens only sometimes, and it seems like it primarily does shortly after altering the database design.

The specific trouble happens at the end, where an MP Health bean will complain that it doesn't have a binding for one of its internal configuration properties. It could be that this is due to not injecting a configuration provider properly, but that doesn't explain why it's only intermittent.

```
org.jboss.weld.exceptions.DeploymentException: Exception List with 2 exceptions:
Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type int with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedField] @Inject @ConfigProperty io.smallrye.health.SmallRyeHealthReporter.timeoutSeconds
  at io.smallrye.health.SmallRyeHealthReporter.timeoutSeconds(SmallRyeHealthReporter.java:0)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:512)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:487)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:501)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:815)
	at org.openntf.xsp.cdi.util.ContainerUtil.lambda$0(ContainerUtil.java:164)
	at org.openntf.xsp.cdi.util.ContainerUtil$$Lambda$3/0x0000000000000000.run(Unknown Source)
	at java.security.AccessController.doPrivileged(AccessController.java:682)
	at org.openntf.xsp.cdi.util.ContainerUtil.getContainer(ContainerUtil.java:164)
	at org.openntf.xsp.cdi.impl.WeldApplicationListener.applicationDestroyed(WeldApplicationListener.java:51)
	at com.ibm.xsp.application.ApplicationExImpl.destroy(ApplicationExImpl.java:384)
	at com.ibm.xsp.controller.FacesControllerImpl.destroy(FacesControllerImpl.java:309)
	at com.ibm.xsp.webapp.FacesServlet.destroyFacesController(FacesServlet.java:742)
	at com.ibm.xsp.webapp.FacesServlet.destroy(FacesServlet.java:401)
	at com.ibm.xsp.webapp.DesignerFacesServlet.destroy(DesignerFacesServlet.java:113)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doDestroyModule(NSFComponentModule.java:675)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.destroyModule(ComponentModule.java:548)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.destroyModule(NSFComponentModule.java:159)
	at com.ibm.domino.xsp.module.nsf.NSFService.doRestartModule(NSFService.java:782)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:738)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
Exception 1 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type String with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedField] @Inject @ConfigProperty io.smallrye.health.AsyncHealthCheckFactory.uncheckedExceptionDataStyle
  at io.smallrye.health.AsyncHealthCheckFactory.uncheckedExceptionDataStyle(AsyncHealthCheckFactory.java:0)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:512)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:487)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:501)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:815)
	at org.openntf.xsp.cdi.util.ContainerUtil.lambda$0(ContainerUtil.java:164)
	at org.openntf.xsp.cdi.util.ContainerUtil$$Lambda$3/0x0000000000000000.run(Unknown Source)
	at java.security.AccessController.doPrivileged(AccessController.java:682)
	at org.openntf.xsp.cdi.util.ContainerUtil.getContainer(ContainerUtil.java:164)
	at org.openntf.xsp.cdi.impl.WeldApplicationListener.applicationDestroyed(WeldApplicationListener.java:51)
	at com.ibm.xsp.application.ApplicationExImpl.destroy(ApplicationExImpl.java:384)
	at com.ibm.xsp.controller.FacesControllerImpl.destroy(FacesControllerImpl.java:309)
	at com.ibm.xsp.webapp.FacesServlet.destroyFacesController(FacesServlet.java:742)
	at com.ibm.xsp.webapp.FacesServlet.destroy(FacesServlet.java:401)
	at com.ibm.xsp.webapp.DesignerFacesServlet.destroy(DesignerFacesServlet.java:113)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doDestroyModule(NSFComponentModule.java:675)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.destroyModule(ComponentModule.java:548)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.destroyModule(NSFComponentModule.java:159)
	at com.ibm.domino.xsp.module.nsf.NSFService.doRestartModule(NSFService.java:782)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:738)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:518)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:487)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:501)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:815)
	at org.openntf.xsp.cdi.util.ContainerUtil.lambda$0(ContainerUtil.java:164)
	at org.openntf.xsp.cdi.util.ContainerUtil$$Lambda$3/0x0000000000000000.run(Unknown Source)
	at java.security.AccessController.doPrivileged(AccessController.java:682)
	at org.openntf.xsp.cdi.util.ContainerUtil.getContainer(ContainerUtil.java:164)
	at org.openntf.xsp.cdi.impl.WeldApplicationListener.applicationDestroyed(WeldApplicationListener.java:51)
	at com.ibm.xsp.application.ApplicationExImpl.destroy(ApplicationExImpl.java:384)
	at com.ibm.xsp.controller.FacesControllerImpl.destroy(FacesControllerImpl.java:309)
	at com.ibm.xsp.webapp.FacesServlet.destroyFacesController(FacesServlet.java:742)
	at com.ibm.xsp.webapp.FacesServlet.destroy(FacesServlet.java:401)
	at com.ibm.xsp.webapp.DesignerFacesServlet.destroy(DesignerFacesServlet.java:113)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doDestroyModule(NSFComponentModule.java:675)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.destroyModule(ComponentModule.java:548)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.destroyModule(NSFComponentModule.java:159)
	at com.ibm.domino.xsp.module.nsf.NSFService.doRestartModule(NSFService.java:782)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:738)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
	Suppressed: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type int with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedField] @Inject @ConfigProperty io.smallrye.health.SmallRyeHealthReporter.timeoutSeconds
  at io.smallrye.health.SmallRyeHealthReporter.timeoutSeconds(SmallRyeHealthReporter.java:0)
		at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
		at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
		at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
		at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
		at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
		at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:512)
		... 23 more
	Suppressed: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type String with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedField] @Inject @ConfigProperty io.smallrye.health.AsyncHealthCheckFactory.uncheckedExceptionDataStyle
  at io.smallrye.health.AsyncHealthCheckFactory.uncheckedExceptionDataStyle(AsyncHealthCheckFactory.java:0)
		at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
		at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
		at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
		at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
		at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
		at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:512)
		... 23 more
```

**Comment by jesse-gallagher** [comment]
This happens almost always after an app design change. I'm not sure why, as the entire CDI container should be rebuilt in that case, but it does seem fairly consistent.

**Comment by jesse-gallagher** [comment]
This _doesn't_ seem to be related to a load-order problem of contributed CDI components, which makes sense: the container is rebuilt as expected and all class contributors are evaluated in the same order.

I also suspected that maybe contributing `ConfigProducer` explicitly from MP Config would do it, but that creates an invalid CDI configuration on first launch.

**Comment by jesse-gallagher** [comment]
This seems like trouble with Extension-based CDI bindings in general: it shows up for the internal ones above as well as for app-specific config and JNoSQL bindings. It's like the extensions aren't re-running properly.

**Comment by jesse-gallagher** [comment]
The trouble seems to almost definitely be that the collection of CDI Extensions contributed by the services are somehow different:

```
adding extensions: [io.smallrye.faulttolerance.FaultToleranceExtension@f634e5e4]
adding extensions: [io.smallrye.config.inject.ConfigExtension@f4e01f81]
adding extensions: []
adding extensions: [org.jboss.resteasy.microprofile.client.RestClientExtension@638ed5b1]
adding extensions: [org.jboss.resteasy.cdi.ResteasyCdiExtension@5331ec29]
adding extensions: [io.smallrye.metrics.setup.MetricCdiInjectionExtension@fe8fd28f]
adding extensions: []
adding extensions: null
adding extensions: [ClassMappingExtension{classConverter=org.eclipse.jnosql.mapping.reflection.ClassConverter@95556c09, mappings-size=0, classes={}}, org.eclipse.jnosql.mapping.document.spi.DocumentExtension@623ae39c]
adding extensions: [org.eclipse.krazo.cdi.KrazoCdiExtension@e208add1]
```
After reload:

```
adding extensions: []
adding extensions: null
adding extensions: []
adding extensions: []
adding extensions: [org.jboss.resteasy.cdi.ResteasyCdiExtension@f4951b01]
adding extensions: [io.smallrye.metrics.setup.MetricCdiInjectionExtension@f55bf6c3]
adding extensions: []
adding extensions: null
adding extensions: []
adding extensions: [org.eclipse.krazo.cdi.KrazoCdiExtension@72ef4c42]
```
