### ISSUE TITLE
Investigate adding Apache Commons Logging

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#146]
It looks like this is used by the MP Rest Client, as seen in the integration tests:

```
[
            "java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory cannot be found by org.apache.wink_1.1.2.20211117-2131",
            "  at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)",
            "  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)",
            "  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)",
            "  at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)",
            "  at java.lang.ClassLoader.loadClass(ClassLoader.java:882)",
            "  at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82)",
            "  at org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:91)",
            "  at org.jboss.resteasy.client.jaxrs.engines.ClientHttpEngineBuilder43.build(ClientHttpEngineBuilder43.java:74)",
            "  at org.jboss.resteasy.client.jaxrs.internal.ResteasyClientBuilderImpl.build(ResteasyClientBuilderImpl.java:416)",
            "  at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(RestClientBuilderImpl.java:364)",
            "  at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(RestClientBuilderImpl.java:388)",
            "  at rest.RestClientExample.get(RestClientExample.java:60)",
            "  at org.jboss.weld.generated.proxies.default.RestClientExample$Proxy$_$$_WeldClientProxy.get(Unknown Source)",
            "  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
            "  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
            "  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
            "  at java.lang.reflect.Method.invoke(Method.java:498)",
            "  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)",
            "  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$292/0x0000000000000000.get(Unknown Source)",
            "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$285/0x0000000000000000.run(Unknown Source)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$286/0x0000000000000000.get(Unknown Source)",
            "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)",
            "  at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)",
            "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
            "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.doService(FacesJAXRSServletContainer.java:72)",
            "  at org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet.service(AbstractXspLifecycleServlet.java:133)",
            "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.service(FacesJAXRSServletContainer.java:55)",
            "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
            "  at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:65)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)",
            "  at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)"
        ]
```

**Comment by jesse-gallagher** [comment]
We _do_ package Commons Logging, but it looks like this is being bound to the Wink-packaged HttpClient when deployed to the filesystem.
