### ISSUE TITLE
 Unsatisfied dependencies for type Session with qualifiers @Named at injection point [BackedAnnotatedField] @Inject @Named rest.DominoObjectsSample.session

### ISSUE THREAD

**Issue by uwebrahm** [OpenNTF/org.openntf.xsp.jakartaee#147]
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM: Exception 0 :
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type Session with qualifiers @Named
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:   at injection point [BackedAnnotatedField] @Inject @Named rest.DominoObjectsSample.session
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:   at rest.DominoObjectsSample.session(DominoObjectsSample.java:0)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:512)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:487)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:501)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.jboss.weld.environment.se.Weld.initialize(Weld.java:815)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.openntf.xsp.cdi.util.ContainerUtil.lambda$0(ContainerUtil.java:165)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.openntf.xsp.cdi.util.ContainerUtil$$Lambda$378/0x0000000000000000.run(Unknown Source)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at java.security.AccessController.doPrivileged(AccessController.java:682)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.openntf.xsp.cdi.util.ContainerUtil.getContainer(ContainerUtil.java:165)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.openntf.xsp.cdi.impl.ContainerUtilProvider.getContainer(ContainerUtilProvider.java:42)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.openntf.xsp.cdi.provider.NSFCDIProvider.getCDI(NSFCDIProvider.java:79)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at jakarta.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:77)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at jakarta.enterprise.inject.spi.CDI.current(CDI.java:64)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at org.openntf.xsp.cdi.impl.CDIResolver.resolveVariable(CDIResolver.java:59)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.javascript.ServerSideLocalObject.resolveVariable(ServerSideLocalObject.java:97)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.javascript.ServerSideLocalObject.resolveAttribute(ServerSideLocalObject.java:73)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.javascript.AbstractLocalObject._get(AbstractLocalObject.java:119)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.javascript.AbstractLocalObject.getPropertyReference(AbstractLocalObject.java:101)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.engine.ProgramContext.findGlobalScopeIdentifier(ProgramContext.java:143)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.engine.ProgramContext.findIdentifier(ProgramContext.java:134)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.ASTTree.ASTIdentifier.interpret(ASTIdentifier.java:105)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.ASTTree.ASTNew.interpret(ASTNew.java:99)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.ASTTree.ASTArgumentList.interpretArguments(ASTArgumentList.java:65)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.types.FBSObject.call(FBSObject.java:153)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.ASTTree.ASTCall.interpret(ASTCall.java:197)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.ASTTree.ASTProgram.interpret(ASTProgram.java:119)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.ASTTree.ASTProgram.interpretEx(ASTProgram.java:139)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.JSExpression._interpretExpression(JSExpression.java:435)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.JSExpression.access$1(JSExpression.java:424)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.JSExpression$2.run(JSExpression.java:414)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at java.security.AccessController.doPrivileged(AccessController.java:774)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.JSExpression.interpretExpression(JSExpression.java:410)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.JSExpression.evaluateValue(JSExpression.java:251)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.jscript.JSExpression.evaluateValue(JSExpression.java:234)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.javascript.JavaScriptInterpreter.interpret(JavaScriptInterpreter.java:222)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.binding.javascript.JavaScriptMethodBinding.invoke(JavaScriptMethodBinding.java:111)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.component.UIViewRootEx.initBeforeContents(UIViewRootEx.java:1755)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.page.compiled.AbstractCompiledPage.initComponent(AbstractCompiledPage.java:333)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.page.compiled.AbstractCompiledPage.createTree(AbstractCompiledPage.java:256)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.page.compiled.AbstractCompiledPage.createViewRoot(AbstractCompiledPage.java:167)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.application.ViewHandlerExImpl._createViewRoot(ViewHandlerExImpl.java:550)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.application.ViewHandlerExImpl.createViewRoot(ViewHandlerExImpl.java:596)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.application.ViewHandlerExImpl.doCreateView(ViewHandlerExImpl.java:144)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.application.ViewHandlerEx.createView(ViewHandlerEx.java:90)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.webapp.FacesServlet.serviceView(FacesServlet.java:254)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.webapp.FacesServletEx.serviceView(FacesServletEx.java:157)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.webapp.FacesServlet.service(FacesServlet.java:163)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.webapp.FacesServletEx.service(FacesServletEx.java:138)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.xsp.webapp.DesignerFacesServlet.service(DesignerFacesServlet.java:103)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)
[1A9C:000B-1AD0] 02/17/2022 12:48:17 AM  HTTP JVM:  at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)

**Comment by jesse-gallagher** [comment]
What are the versions of the JEE support plugins and the example NSF in this case? In the 2.4.0 development line, I ended up changing the name of the `Session` object provider to `dominoSession` to avoid conflict with JSF's `session` variable.

**Comment by uwebrahm** [comment]
I'm using the 2.3 version of your JEE support plugin. I was trying to setup a REST api in a specific database of mine that needed such a nice feature. I've imported the XPages plugin features into the servers updatesite.nsf and put the corresponding org.openntf.xsp.jakartaee-develop\org.openntf.xsp.jakartaee-develop\eclipse\nsfs\nsf-jakartaee-example\odp\Code\Java\rest\DominoObjectsSample.java file into the database. This should have been a minified version as a little test. The side effect here is, that all my custom XPages now fail to run in my database that has just this one Java file added. You might not run into these problems as you have put everything nice and clean into your example nsf. Do I need anything else to configure in order to get this going? Is there another config file somewhere that needs to be present to just run the bare bones DominoObjectsSample,java?

**Comment by jesse-gallagher** [comment]
Ah, so it probably is indeed the renaming of the variable. In that class, there should be a line like `@Named("dominoSession")` - if you change that to `@Named("session")`, then that should work with 2.3.
