### ISSUE TITLE
Observed Provider org.glassfish.json.JsonProviderImpl not found 

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#15]
```
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM: org.jboss.resteasy.spi.UnhandledException: javax.json.JsonException: Provider org.glassfish.json.JsonProvider
Impl not found
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:78)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:222)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:193)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:455)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$132.000000004A030E60.run(Unknown Source)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$133.000000003FEC1140.get(Unknown Source)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestC
ontext.java:355)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatch
er.java:227)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56
)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51
)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.service(FacesJAXRSServletContainer.java:96)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.
java:877)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java
:820)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:662)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:482)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM: Caused by:
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM: javax.json.JsonException: Provider org.glassfish.json.JsonProviderImpl not found
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at javax.json.spi.JsonProvider.provider(JsonProvider.java:75)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at javax.json.Json.createObjectBuilder(Json.java:275)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at com.tlcc.CalendarResource.set(CalendarResource.java:17)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.weld.proxies.CalendarResource$Proxy$_$$_WeldClientProxy.set(Unknown Source)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at java.lang.reflect.Method.invoke(Method.java:508)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:509)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:39
9)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:363)

[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$134.000000004A0593C0.get(Unknown Source)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestC
ontext.java:355)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:365)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:337)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:310)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:439)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      ... 23 more
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM: Caused by:
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM: java.lang.ClassNotFoundException: org.glassfish.json.JsonProviderImpl
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at java.lang.Class.forNameImpl(Native Method)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at java.lang.Class.forName(Class.java:339)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      at javax.json.spi.JsonProvider.provider(JsonProvider.java:72)
[10D8:000E-1128] 08/22/2019 04:54:23 PM  HTTP JVM:      ... 40 more
```

**Comment by jesse-gallagher** [comment]
This shows up in a couple places, and probably needs some additional adapters. Part of the trouble is that the `org.glassfish.json` package is (properly) not exported. It'll need a bridge, though.

**Comment by jesse-gallagher** [comment]
The trouble could be that both the JSON API bundle and the Glassfish implementation bundle include the API classes.
