### ISSUE TITLE
NoClassDefFoundError: com.fasterxml.jackson.core.type.TypeReference

### ISSUE THREAD

**Issue by perlausten** [OpenNTF/org.openntf.xsp.jakartaee#172]
I am converting an existing application from using a home made JAX-RS solution to using this project. GET requests fails with this stack trace:

```
07-03-22 17:52: Exception Thrown
java.lang.NoClassDefFoundError: com.fasterxml.jackson.core.type.TypeReference
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:397)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:358)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:471)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:954)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:899)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.loadClass(ModuleClassLoader.java:419)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader.loadClass(ModuleClassLoader.java:229)
	at org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet.lambda$3(AbstractXspLifecycleServlet.java:246)
	at org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet$$Lambda$186/0x0000000000000000.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet.buildMatchingClasses(AbstractXspLifecycleServlet.java:261)
	at org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet.init(AbstractXspLifecycleServlet.java:103)
	at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.init(NewHttpServletWrapper.java:57)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.createServlet(ComponentModule.java:453)
	at org.openntf.xsp.jaxrs.JAXRSServletFactory.getExecutorServlet(JAXRSServletFactory.java:122)
	at org.openntf.xsp.jaxrs.JAXRSServletFactory.getServletMatch(JAXRSServletFactory.java:109)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:811)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:76)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:1)
	at com.mindoo.domino.jna.gc.NotesGC$3.run(NotesGC.java:511)
	at java.security.AccessController.doPrivileged(AccessController.java:682)
	at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:506)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService.doService(DominoJNAHttpService.java:68)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
Caused by: java.lang.ClassNotFoundException: Cannot find class com.fasterxml.jackson.core.type.TypeReference in NSF
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:519)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:954)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:899)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.loadClass(ModuleClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:882)
	... 43 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.type.TypeReference
	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:492)
	... 47 more
```

**Comment by perlausten** [comment]
It works now! It was installation issues in Domino Designer where not all plugins were propertly installed/upgraded. This had the effect that I was not able to select all required libraries in xsp.properties (including for instance org.openntf.xsp.jakarta.servlet).

**Comment by jesse-gallagher** [comment]
Hmm, interesting. I'm not sure what would specifically cause it, but maybe it was a case of Designer not actually recompiling the NSF and thereby not removing some class references or something. We'll have to keep an eye out in case it's actually a persisting problem, but this is a good outcome for now.

**Comment by perlausten** [comment]
My installation issues in Domino Designer started when I accidentally clicked No to one of the plugins when upgrading to 2.5. I apparently forgot about it and started testing when this issue occurred. So hopefully we should not see this kind of issue again 😄
