### ISSUE TITLE
OpenAPI generation hits exception for Anonymous with "No Access" but "Read Public Documents" checked

### ISSUE THREAD

**Issue by perlausten** [OpenNTF/org.openntf.xsp.jakartaee#186]
The openapi call fails for anonymous with a "Notes error: You are not authorized to perform that operation" which is caused by the AbstractOpenAPIResource.getVersionNumber call.

Stacktrace from the JSON result from the openapi call:
```
{
    "message": "lotus.domino.NotesException: Notes error: You are not authorized to perform that operation",
    "stackTrace": [
        [
            "lotus.domino.NotesException: Notes error: You are not authorized to perform that operation",
            "  at lotus.domino.local.NoteCollection.NbuildCollection(Native Method)",
            "  at lotus.domino.local.NoteCollection.buildCollection(Unknown Source)",
            "  at org.openntf.xsp.microprofile.openapi.AbstractOpenAPIResource.getVersionNumber(AbstractOpenAPIResource.java:127)",
            "  at org.openntf.xsp.microprofile.openapi.AbstractOpenAPIResource.buildOpenAPI(AbstractOpenAPIResource.java:94)",
            "  at org.openntf.xsp.microprofile.openapi.OpenAPIJSONResource.get(OpenAPIJSONResource.java:39)",
            "  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
            "  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
            "  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
            "  at java.lang.reflect.Method.invoke(Method.java:498)",
            "  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)",
            "  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker$$Lambda$282/0x0000000000000000.get(Unknown Source)",
            "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$274/0x0000000000000000.run(Unknown Source)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$275/0x0000000000000000.get(Unknown Source)",
            "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)",
            "  at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)",
            "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
            "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.doService(FacesJAXRSServletContainer.java:72)",
            "  at org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet.service(AbstractXspLifecycleServlet.java:129)",
            "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.service(FacesJAXRSServletContainer.java:55)",
            "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
            "  at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:112)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:76)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:1)",
            "  at com.mindoo.domino.jna.gc.NotesGC$3.run(NotesGC.java:557)",
            "  at java.security.AccessController.doPrivileged(AccessController.java:682)",
            "  at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:552)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService.doService(DominoJNAHttpService.java:68)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)",
            "  at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)"
        ]
    ]
}
```

The openapi call works when using an authorized user.

**Comment by perlausten** [comment]
Access for Anonymous is "No access" (with "Read public documents" checked)
