### ISSUE TITLE
Observed Weld-related error that prevents the XPage runtime from loading

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#19]
```
javax.servlet.ServletException: com.ibm.xsp.FacesExceptionEx: java.lang.IllegalStateException: WELD-ENV-000035: Class path entry does not exist or cannot be read: STPolicy.jar
	at com.ibm.xsp.webapp.FacesServlet.init(FacesServlet.java:96)
	at com.ibm.xsp.webapp.FacesServletEx.init(FacesServletEx.java:73)
	at com.ibm.xsp.webapp.DesignerFacesServlet.init(DesignerFacesServlet.java:64)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.createServlet(ComponentModule.java:422)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.createServlet(ComponentModule.java:401)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.getXspEngineServlet(NSFComponentModule.java:1273)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.getServlet(NSFComponentModule.java:1397)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:793)
	at com.ibm.de
		signer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:577)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1319)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:662)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:482)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:357)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:313)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
Caused by: com.ibm.xsp.FacesExceptionEx: java.lang.IllegalStateException: WELD-ENV-000035: Class path entry does not exist or cannot be read: STPolicy.jar
	at com.ibm.xsp.webapp.FacesServlet.createFacesController(FacesServlet.java:679)
	at com.ibm.xsp.webapp.DesignerFacesServlet.getContextFacesControll
		er(DesignerFacesServlet.java:124)
	at com.ibm.xsp.webapp.FacesServlet.getFacesController(FacesServlet.java:637)
	at com.ibm.xsp.webapp.FacesServlet.init(FacesServlet.java:85)
	... 14 more
Caused by: java.lang.IllegalStateException: WELD-ENV-000035: Class path entry does not exist or cannot be read: STPolicy.jar
	at org.jboss.weld.environment.deployment.discovery.ClassPathBeanArchiveScanner.scan(ClassPathBeanArchiveScanner.java:85)
	at org.jboss.weld.environment.deployment.discovery.AbstractDiscoveryStrategy.performDiscovery(AbstractDiscoveryStrategy.java:93)
	at org.jboss.weld.environment.se.Weld.createDeployment(Weld.java:934)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:774)
	at org.openntf.xsp.cdi.util.ContainerUtil.getContainer(ContainerUtil.java:95)
	at org.openntf.xsp.cdi.impl.WeldApplicationListener.applicationCreated(WeldApplicationListener.java:44)
	
		at com.ibm.xsp.application.ApplicationExImpl.init(ApplicationExImpl.java:235)
	at com.ibm.xsp.application.ApplicationExImpl.<init>(ApplicationExImpl.java:153)
	at com.ibm.xsp.application.DesignerApplicationEx.<init>(DesignerApplicationEx.java:68)
	at com.ibm.xsp.application.DesignerApplicationFactoryImpl.createApplicationInstance(DesignerApplicationFactoryImpl.java:68)
	at com.ibm.xsp.application.ApplicationFactoryImpl.createApplicationEx(ApplicationFactoryImpl.java:99)
	at com.ibm.xsp.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:70)
	at com.ibm.xsp.controller.FacesControllerImpl.init(FacesControllerImpl.java:104)
	at com.ibm.xsp.controller.DesignerFacesController.init(DesignerFacesController.java:132)
	at com.ibm.xsp.webapp.FacesServlet.initializeFacesController(FacesServlet.java:692)
	at com.ibm.xsp.webapp.FacesServlet.createFacesController(FacesSer
```

**Comment by jesse-gallagher** [comment]
The trouble is to do with scanning through the active Java classpath - if an entry is invalid or inaccessible, it throws up its hands. Unfortunately, it's in a code path where I don't think we can realistically work around it, so it'll have to be more of a "known issue".
