### ISSUE TITLE
RestClientBuilder fails with "Provider for RuntimeDelegate cannot be found"

### ISSUE THREAD

**Issue by perlausten** [OpenNTF/org.openntf.xsp.jakartaee#267]
I am using RestClientBuilder to build a client to post JSON to an endpoint. The code has stopped working at some point.

I am doing this but the build call fails:

```
URI uri = URI.create(event.getTargetUrl());
WebhookGenericService service = RestClientBuilder.newBuilder().baseUri(uri).build(WebhookGenericService.class);
service.post(jsonMap);
```

This is the stack trace:

```
java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.ext.RuntimeDelegate cannot be found
	at jakarta.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:113)
	at jakarta.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:84)
	at jakarta.ws.rs.core.MediaType.valueOf(MediaType.java:172)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl.defaultConsumes(ProxyBuilderImpl.java:102)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ProxyBuilderImpl.defaultConsumes(ProxyBuilderImpl.java:28)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(RestClientBuilderImpl.java:370)
	at org.jboss.resteasy.microprofile.client.RestClientBuilderImpl.build(RestClientBuilderImpl.java:388)
	at dk.fmcgsolutions.webhooks.WebhookClient.send(WebhookClient.java:115)
	at dk.fmcgsolutions.product.AsyncWebhookEvent.run(AsyncWebhookEvent.java:40)
```

I hope you have an idea to a fix. If not, then I will have to dig some more into what version of your project used when it worked.

**Comment by jesse-gallagher** [comment]
Hmm, is this running in a separate thread of one kind or another? That could be the trouble if so: I haven't properly gotten the Rest Client working in contexts other than a normal JAX-RS request.

If it used to work in this case, what version was that and which version are you using now? It's possible that the provider mechanism changed somewhere along the line.

**Comment by perlausten** [comment]
It's running as an asynchronous call but used to work. I will take a closer look and see if I can find the version used when it was working. 

My investigation so far: It fails with the 2.6 release and also fails with 2.5 from late April.

**Comment by jesse-gallagher** [comment]
I'll have to look into it when I get a chance. I'm actually a little surprised that it used to work: I've had to jump through some hoops to get these contexts recognized as associated with an NSF at all, and threads kind of throw that for a loop. It's possible that something broke in here, but it's also possible that the fact that it worked in the past was sort of a fluke.

In the mean time, maybe it'd make sense to do the Rest Client building before spawning the task, and then passing it in to the task to use later. That could likely pick up and retain all the context it needs, regardless of version.

This may also be a good impetus for me to look into https://github.com/OpenNTF/org.openntf.xsp.jakartaee/issues/77 , which is intended to make contexts like this work in multiple threads.

**Comment by perlausten** [comment]
If I run my Rest Client logic directly (so not via XOTS), it still fails.

I will later try your example in the "XPages JEE Example" database.

**Comment by perlausten** [comment]
After completely deleting the disabled older version of the plugins and restarting the server, it now works on my local test server! So somehow several versions of the plugins must have caused a conflict.

The MicroProfile - Rest Client GET example in the "XPages JEE Example" database also works on my local test server.

However it still fails on the production server even though I have tried several times removing/re-adding the plugin and restarting the server and HTTP. I will continue my investigation.

**Comment by jesse-gallagher** [comment]
How are you using XOTS here, by the way? Is it just as a means to fire off async tasks, or is it acting as a configurable scheduler? I ask because the Concurrency API I’m looking at covers ExecutorServices and explicitly-scheduled tasks, but not quite something like “run at 9 AM every weekday”.

**Comment by perlausten** [comment]
I'm using XOTS to fire off async tasks.

**Comment by jesse-gallagher** [comment]
My hope is that the Concurrency stuff I’m adding will help make this sort of thing officially supported and not just a fluke when it will or won’t work. I haven’t gotten to making sure the JAX-RS context is brought over, but it’s next on the list.

**Comment by perlausten** [comment]
With a build from July 18 the RestClientBuilder now works again (from my async XOTS request triggered by XPages)
