### ISSUE TITLE
Encountered NoPublicAccess exception during Weld initialization

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#292]
This is in a database that has some pages marked for Public Access.

```
log.nsf:
21-07-2022 12:00:35   HTTP JVM: CLFAD0211E: Exception thrown. For more detailed information, please consult error-log-0.xml located in C:/IBM/Domino/data/domino/workspace/logs
21-07-2022 12:00:35   HTTP JVM: CLFAD0246E: Exception occurred servicing request for: /fmcg/pa-dev.nsf/index.xsp - HTTP Code: 500. For more detailed information, please consult error-log-0.xml located in C:/IBM/Domino/data/domino/workspace/logs
21-07-2022 12:00:35   HTTP Web Server: Command Not Handled Exception [/fmcg/pa-dev.nsf] Anonymous

Stack trace from IBM_TECHNICAL_SUPPORT\xpages*.log:
21-07-22 12:00: Exception Thrown
com.ibm.xsp.FacesExceptionEx: com.ibm.xsp.acl.NoAccessSignal: com.ibm.commons.util.NoPublicAccess
	at com.ibm.xsp.context.FacesContextExImpl.<init>(FacesContextExImpl.java:317)
	at com.ibm.xsp.domino.context.DominoFacesContext.<init>(DominoFacesContext.java:32)
	at com.ibm.xsp.domino.context.DominoFacesContextFactoryImpl.getFacesContext(DominoFacesContextFactoryImpl.java:67)
	at org.openntf.domino.xsp.adapter.ODAFacesContextFactory.getFacesContext(ODAFacesContextFactory.java:72)
	at com.ibm.xsp.controller.FacesControllerImpl.getFacesContext(FacesControllerImpl.java:184)
	at com.ibm.xsp.webapp.FacesServlet.getFacesContext(FacesServlet.java:411)
	at com.ibm.xsp.webapp.FacesServlet.service(FacesServlet.java:144)
	at com.ibm.xsp.webapp.FacesServletEx.service(FacesServletEx.java:138)
	at com.ibm.xsp.webapp.DesignerFacesServlet.service(DesignerFacesServlet.java:103)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:76)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:1)
	at com.mindoo.domino.jna.gc.NotesGC$3.run(NotesGC.java:511)
	at java.security.AccessController.doPrivileged(AccessController.java:682)
	at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:506)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService.doService(DominoJNAHttpService.java:68)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:298)
Caused by: com.ibm.xsp.acl.NoAccessSignal: com.ibm.commons.util.NoPublicAccess
	at com.ibm.domino.xsp.module.nsf.NotesContext.checkAccess(NotesContext.java:1766)
	at com.ibm.domino.xsp.module.nsf.NotesContext.serverProcessSignedResource(NotesContext.java:1026)
	at com.ibm.domino.xsp.module.nsf.NotesContext.setSignerSessionRights(NotesContext.java:983)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:468)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:954)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:899)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.loadClass(ModuleClassLoader.java:419)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader.loadClass(ModuleClassLoader.java:229)
	at org.jboss.weld.resources.AbstractClassLoaderResourceLoader.classForName(AbstractClassLoaderResourceLoader.java:40)
	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadClass(AnnotatedTypeLoader.java:83)
	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:63)
	at org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadAnnotatedType(FastAnnotatedTypeLoader.java:108)
	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:87)
	at org.jboss.weld.bootstrap.BeanDeployer.addClasses(BeanDeployer.java:134)
	at org.jboss.weld.bootstrap.BeanDeployment.createClasses(BeanDeployment.java:198)
	at org.jboss.weld.bootstrap.WeldStartup.startInitialization(WeldStartup.java:417)
	at org.jboss.weld.bootstrap.WeldBootstrap.startInitialization(WeldBootstrap.java:79)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:813)
	at org.openntf.xsp.cdi.util.ContainerUtil.lambda$1(ContainerUtil.java:189)
	at <unknown class>.run(Unknown Source)
	at java.security.AccessController.doPrivileged(AccessController.java:682)
	at org.openntf.xsp.cdi.util.ContainerUtil.lambda$0(ContainerUtil.java:169)
	at <unknown class>.get(Unknown Source)
	at org.openntf.xsp.cdi.util.ContainerUtil.withLock(ContainerUtil.java:556)
	at org.openntf.xsp.cdi.util.ContainerUtil.getContainer(ContainerUtil.java:142)
	at org.openntf.xsp.cdi.impl.ContainerUtilProvider.getContainer(ContainerUtilProvider.java:42)
	at org.openntf.xsp.cdi.provider.NSFCDIProvider.getCDI(NSFCDIProvider.java:124)
	at jakarta.enterprise.inject.spi.CDI.current(CDI.java:64)
	at org.openntf.xsp.jakarta.transaction.servlet.AbstractTransactionJndiConfigurator.pushTransaction(AbstractTransactionJndiConfigurator.java:43)
	at org.openntf.xsp.jakarta.transaction.nsf.TransactionRequestCustomizerFactory.initializeParameters(TransactionRequestCustomizerFactory.java:37)
	at com.ibm.xsp.context.FacesContextExImpl.getRequestParameters(FacesContextExImpl.java:503)
	at com.ibm.xsp.context.FacesContextExImpl.isRunningContext(FacesContextExImpl.java:518)
	at com.ibm.xsp.context.FacesContextExImpl.<init>(FacesContextExImpl.java:299)
	... 25 more
Caused by: com.ibm.commons.util.NoPublicAccess
	... 58 more
```

**Comment by jesse-gallagher** [comment]
The trouble comes immediately from a timing issue where the Transaction JNDI configurator uses the current CDI context to find a UserTransaction, but that kicks off all the extra CDI init when it's the first request. That's very excessive, especially considering that DominoUserTransaction doesn't even contain any instance data. It'd make sense to set this to a new or shared instance instead of using CDI.
