### ISSUE TITLE
Observed ClassNotFoundException in EL on first XPage load after app change

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#294]
I saw this a couple times in a basic app: changing xsp.properties or an XPage would cause the next page load to emit this exception:

```
java.lang.NoClassDefFoundError: org.openntf.xsp.el.ELBindingFactory (initialization failure)
	at java.lang.J9VMInternals.initializationAlreadyFailed(J9VMInternals.java:95)
	at org.openntf.xsp.el.ELApplicationListener.applicationCreated(ELApplicationListener.java:33)
	at org.openntf.xsp.el.ELApplicationListener.applicationRefreshed(ELApplicationListener.java:47)
	at com.ibm.xsp.application.ApplicationExImpl.refresh(ApplicationExImpl.java:196)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.refresh(NSFComponentModule.java:926)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:768)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:302)
Caused by: jakarta.el.ELException: Provider com.sun.el.ExpressionFactoryImpl not found
	at jakarta.el.FactoryFinder.newInstance(FactoryFinder.java:59)
	at jakarta.el.FactoryFinder.find(FactoryFinder.java:135)
	at jakarta.el.ExpressionFactory.newInstance(ExpressionFactory.java:140)
	at jakarta.el.ExpressionFactory.newInstance(ExpressionFactory.java:110)
	at org.openntf.xsp.el.ELBindingFactory.<clinit>(ELBindingFactory.java:46)
	... 12 more
Caused by: java.lang.ClassNotFoundException: Cannot find class com.sun.el.ExpressionFactoryImpl in NSF
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:519)
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:954)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:899)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.loadClass(ModuleClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:882)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader.loadClass(ModuleClassLoader.java:215)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:882)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader.loadClass(ModuleClassLoader.java:226)
	at jakarta.el.FactoryFinder.newInstance(FactoryFinder.java:43)
	... 16 more
```

Subsequent page loads work without issue.

**Comment by jesse-gallagher** [comment]
This problem seems to have been caused by a pretty-unusual situation: I had a client project's OSGi bundle set installed on the server, which only includes a subset of this project's features. Though it _should_ have worked logically, the project makes no guarantee of functionality when sliced apart like that, so it's not critical to investigate.
