### ISSUE TITLE
WELD-001303: No active contexts for scope type jakarta.enterprise.context.RequestScoped

### ISSUE THREAD

**Issue by perlausten** [OpenNTF/org.openntf.xsp.jakartaee#295]
I have occasionally seen this stack trace during development after having changed code and rebuilt an app several times. I see it when testing a JAX-RS REST endpoint but XPages still works. I have to restart HTTP to get the endpoint to work again.

```
{
    "message": "org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type jakarta.enterprise.context.RequestScoped",
    "stackTrace": [
        [
            "org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type jakarta.enterprise.context.RequestScoped",
            "  at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:647)",
            "  at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:89)",
            "  at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:164)",
            "  at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)",
            "  at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:87)",
            "  at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:105)",
            "  at org.eclipse.krazo.jaxrs.JaxRsContextProducer$Proxy$_$$_WeldClientProxy.setConfiguration(Unknown Source)",
            "  at org.eclipse.krazo.jaxrs.PreMatchingRequestFilter.filter(PreMatchingRequestFilter.java:70)",
            "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:312)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)",
            "  at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)",
            "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
            "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.doService(FacesJAXRSServletContainer.java:77)",
            "  at org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet.service(AbstractXspLifecycleServlet.java:129)",
            "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.service(FacesJAXRSServletContainer.java:58)",
            "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
            "  at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:112)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:76)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:1)",
            "  at com.mindoo.domino.jna.gc.NotesGC$3.run(NotesGC.java:511)",
            "  at java.security.AccessController.doPrivileged(AccessController.java:682)",
            "  at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:506)",
            "  at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService.doService(DominoJNAHttpService.java:68)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)",
            "  at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:298)"
        ]
    ]
}
```

**Comment by jesse-gallagher** [comment]
Hmm, interesting. I don't think I've seen that specifically lately, but I _do_ have a few enhancement issues open that may as a side effect fix this anyway: https://github.com/OpenNTF/org.openntf.xsp.jakartaee/issues/288 and https://github.com/OpenNTF/org.openntf.xsp.jakartaee/issues/287 . I'll bump those up in my queue and see if they fix this.

**Comment by jesse-gallagher** [comment]
As an update, I've done some poking around to get those other issues done to see if it'd fix this, but I haven't been successful in doing either in a way that doesn't generate any new test failures.

**Comment by jesse-gallagher** [comment]
I've been trying again to reproduce this without success. I think I may create a final build of 2.9.0 and then, for 2.10.0-SNAPSHOT or 3.0.0-SNAPSHOT, try some ideas I have around cleaning up the implementation generally. If that works on its own, it's possible it'd also improve this inconsistency in practice.

**Comment by jesse-gallagher** [comment]
All the better!
