### ISSUE TITLE
WELD-001456: Argument bean must not be null

### ISSUE THREAD

**Issue by Sjaksan** [OpenNTF/org.openntf.xsp.jakartaee#317]
We are experiencing issues when using the RESTful service. We regularly receive the message 'WELD-001456: Argument bean must not be null'. I think especially when we work with several people in the same application.
We have also experienced it with the supplied ExampleDatabase from OpenNTF.
It could only reproduce it on two linux servers, on my windows servers I have not been able to reproduce it.
On all the tested servers we use bundle release 2.7.0 and Domino 12.0.1. No extra jars added to the ext folder and no JavaUserClassesExt entry in the notes.ini.

For example from the ExampleDatabase: `jakartaee.nsf/xsp/app/jsonExample/jsonp`

`{
    "message": "org.jboss.weld.exceptions.IllegalArgumentException: WELD-001456: Argument bean must not be null",
    "stackTrace": [
        [
            "org.jboss.weld.exceptions.IllegalArgumentException: WELD-001456: Argument bean must not be null",
            "  at org.jboss.weld.util.Preconditions.checkArgumentNotNull(Preconditions.java:40)",
            "  at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:708)",
            "  at org.jboss.resteasy.cdi.CdiConstructorInjector.construct(CdiConstructorInjector.java:69)",
            "  at org.jboss.resteasy.cdi.CdiConstructorInjector.construct(CdiConstructorInjector.java:75)",
            "  at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:71)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:401)",
            "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$305/0x0000000000000000.run(Unknown Source)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher$$Lambda$306/0x0000000000000000.get(Unknown Source)",
            "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)",
            "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)",
            "  at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)",
            "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)",
            "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
            "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.doService(FacesJAXRSServletContainer.java:77)",
            "  at org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet.service(AbstractXspLifecycleServlet.java:129)",
            "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.service(FacesJAXRSServletContainer.java:58)",
            "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
            "  at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:112)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)",
            "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)",
            "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)",
            "  at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)",
            "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)",
            "  at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)"
        ]
    ]
}`

BTW Great project! 
Gr. Jack

**Comment by jesse-gallagher** [comment]
Hmm, I haven't seen this, but I'll see if I can find a way to reproduce it. In the mean time, could you try this in-development 2.8.0 build? I don't know of any changes that would explicitly affect this, but there's always a chance.

[org.openntf.xsp.jakartaee.updatesite-2.8.0-SNAPSHOT.zip](https://github.com/OpenNTF/org.openntf.xsp.jakartaee/files/9469749/org.openntf.xsp.jakartaee.updatesite-2.8.0-SNAPSHOT.zip)

**Comment by Sjaksan** [comment]
Thx. 
I've tried the 2.8.0 build on our test application and on the example database. In our test application we only use the RESTfull services and we weren't able to reproduce this issue in our test application. 
In your example database we now get "WELD-001333: BeanManager method getBeans() is not available after shutdown" on most pages, as soon as a second user is making requests. Probably caused by the bean injections?

**Comment by jesse-gallagher** [comment]
Interesting indeed. Are you seeing that message from the example DB as well? I'd like to narrow down differences as to why you see these things and I have yet to - things like app timeout settings, etc.

**Comment by Sjaksan** [comment]
Yes, this was also in the example DB. But I can't reproduce now without my colleague. When I try it myself with two browsers, I don't experience this problem. So I'm going to test it again on Monday with my colleague.

**Comment by Sjaksan** [comment]
I have updated to the new 2.8.0 build and we haven't had any 'WELD-001456: Argument bean must not be null' issues again. But on our linux servers we still get "WELD-001333: BeanManager method getBeans() is not available after shutdown" when we access the application with two users. See image: https://raw.githubusercontent.com/Sjaksan/JacksSjizzle/main/jakartaee-WELD-001333.PNG. What information do you need? what do you mean by timeout setting?

**Comment by jesse-gallagher** [comment]
Huh, there's another one I haven't seen and haven't immediately been able to reproduce. Is it consistent, like if you restart the server and immediately access the NSF from two browsers?

As for the app timeout setting, I mean these settings in the Xsp Properties editor on the first tab:

<img width="378" alt="Screen Shot 2022-10-06 at 10 51 07 AM" src="https://user-images.githubusercontent.com/935700/194345535-8ac9860d-04a2-4cf5-8cba-4aca8b34e5e5.png">

Beyond that, have you configured your java.policy/java.pol file to [relax restrictions](https://github.com/OpenNTF/org.openntf.xsp.jakartaee#requirements)? Though I'd like to avoid that being necessary, it is for a couple things for now. I haven't seen trouble with JSON-P specifically, but it's possibly a knock-on effect.

**Comment by Sjaksan** [comment]
We have the default timeout settings, the same as in your image. The java.policy is configured to relaxed. 
After restarting the server we click a couple of times on REST+CDI and we get the correct response, but when a second user clicks on REST+CDI, we get instantly errors.  Some times is the first error different like: java.lang.IllegalStateException: Singleton not set for C1258832:00541D27 => [] or "org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type jakarta.enterprise.context.RequestScoped", followed by the WELD-001333 error.

**Comment by jesse-gallagher** [comment]
I've certainly seen that exception before, but not in recent builds. I'll see if I can find other ways to trigger the behavior locally.

**Comment by Sjaksan** [comment]
I've tested it on a fresh installation of Domino 12.0.1, created two users. And got the same error when the second user clicked on REST+CDI.  
When the second users clicks, i see a Destroying applicatoinGuy! in the log:
10/11/2022 03:28:24 AM  HTTP JVM: Created requestGuy!
10/11/2022 03:28:24 AM  HTTP JVM: Destroying requestGuy!
**10/11/2022 03:28:25 AM  HTTP JVM: Destroying applicationGuy!**

**Comment by jesse-gallagher** [comment]
Hmm, that's interesting - the messages themselves are fine, but it's odd that the bean is destroyed one second after a request. I'd expect that to survive a lot longer, like for half an hour.

Those log files may indeed help - I _suspect_ that they'll just have normal information, but I might be wrong.

In the mean time, I've tried to reproduce this again with a heavy multithreading test, but (unfortunately, in this case) the test passes without issue. I'll keep coming up with scenarios.

**Comment by Sjaksan** [comment]
That's what I thought. I'm waiting for HCL's response. I'll keep you posted if anything comes up.
Thanks so far.
