### ISSUE TITLE
Encountered "Provider for jakarta.ws.rs.client.ClientBuilder cannot be found" in recent builds

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#351]
In the current `develop` stream, this trouble is back, implying a problem with FactoryFinder trying to locate the RestEasy JAX-RS client implementation.

**Comment by jesse-gallagher** [comment]
```json
"java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cannot be found",
      "  at jakarta.ws.rs.client.FactoryFinder.find(FactoryFinder.java:168)",
      "  at jakarta.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:62)",
      "  at bean.RestClientBean.getJsonObjectViaClient(RestClientBean.java:68)",
      "  at org.jboss.weld.generated.proxies.default.RestClientBean$Proxy$_$$_WeldClientProxy.getJsonObjectViaClient(Unknown Source)",
      "  at rest.JaxRsClientExample.get(JaxRsClientExample.java:35)",
      "  at org.jboss.weld.generated.proxies.default.JaxRsClientExample$Proxy$_$$_WeldClientProxy.get(Unknown Source)",
      "  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
      "  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "  at java.lang.reflect.Method.invoke(Method.java:498)",
      "  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)",
      "  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)",
      "  at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)",
      "  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)",
      "  at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)",
      "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
      "  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)",
      "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)",
      "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)",
      "  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)",
      "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)",
      "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)",
      "  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)",
      "  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)",
      "  at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)",
      "  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)",
      "  at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)",
      "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60)",
      "  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)",
      "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
      "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.doService(FacesJAXRSServletContainer.java:77)",
      "  at org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet.service(AbstractXspLifecycleServlet.java:129)",
      "  at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.service(FacesJAXRSServletContainer.java:58)",
      "  at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)",
      "  at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:112)",
      "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)",
      "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)",
      "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)",
      "  at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)",
      "  at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)",
      "  at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)",
      "  at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)",
      "  at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)",
      "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)",
      "  at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)",
      "  at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:302)"
```

**Comment by perlausten** [comment]
I just noticed that am seeing this in the 2.10.0.202303111916 build:

```
java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cannot be found
	jakarta.ws.rs.client.FactoryFinder.find(FactoryFinder.java:168)
	jakarta.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:62)
	dk.fmcgsolutions.images.epdmediastore.client.api.ClientHeaders.getClient(ClientHeaders.java:80)
```

**Comment by jesse-gallagher** [comment]
Huh, interesting... I haven't seen that recently, but I'll check into it.
