### ISSUE TITLE
Observed "NotesContext not initialized for this thread" on console from Concurrency threads

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#362]
I believe these showed up a little while after (successfully) running the MP Rest Client concurrent test.

I'm not sure _why_ it would show up a little while later (or at all, if the call worked) since there's no scheduled or repeating task there. However, this seems to be a valid thing: unlike other times I've seen things like this, I was not actively making changes to the NSF design around when it cropped up. It's likely that this is from an app timeout.

I saw this twice within the same second:

```
Exception in thread "threadFactory-dev/jakarta.nsf-Thread-1"
java.lang.IllegalStateException: NotesContext not initialized for the thread
     at com.ibm.domino.xsp.module.nsf.NotesContext.getCurrent(NotesContext.java:124)
     at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClassesResource(ModuleClassLoader.java:570)
     at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findResource(ModuleClassLoader.java:544)
     at java.lang.ClassLoader.getResource(ClassLoader.java:601)
     at com.ibm.domino.xsp.module.nsf.ModuleClassLoader.getResource(ModuleClassLoader.java:211)
     at java.lang.ClassLoader.getResource(ClassLoader.java:598)
     at org.openntf.xsp.mvc.jaxrs.MvcJaxrsServiceParticipant$KrazoClassLoader.getResource(MvcJaxrsServiceParticipant.java:112)
     at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:721)
     at org.openntf.xsp.mvc.jaxrs.MvcJaxrsServiceParticipant$KrazoClassLoader.getResourceAsStream(MvcJaxrsServiceParticipant.java:125)
     at javax.faces.FactoryFinder.getImplNameFromServices(FactoryFinder.java:506)
     at javax.faces.FactoryFinder.getImplementationInstance(FactoryFinder.java:475)
     at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:276)
     at com.ibm.xsp.application.ApplicationEx._getInstance(ApplicationEx.java:96)
     at com.ibm.xsp.application.ApplicationEx.getInstance(ApplicationEx.java:75)
     at org.openntf.xsp.cdi.provider.ApplicationExCDIContainerLocator.getContainer(ApplicationExCDIContainerLocator.java:39)
     at org.openntf.xsp.cdi.provider.NSFCDIProvider.getCDI(NSFCDIProvider.java:53)
     at jakarta.enterprise.inject.spi.CDI.current(CDI.java:64)
     at org.openntf.xsp.jakarta.transaction.concurrency.TransactionContextSetupParticipant.reset(TransactionContextSetupParticipant.java:63)
     at org.openntf.xsp.jakarta.concurrency.DominoContextSetupProvider.lambda$3(DominoContextSetupProvider.java:72)
     at java.util.ArrayList.forEach(ArrayList.java:1259)
     at org.openntf.xsp.jakarta.concurrency.DominoContextSetupProvider.reset(DominoContextSetupProvider.java:72)
     at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:234)
     at org.openntf.xsp.jakarta.concurrency.NotesManagedThreadFactory$ManagedNotesThread.run(NotesManagedThreadFactory.java:76)
```

**Comment by jesse-gallagher** [comment]
This could be a timing thing with ApplicationListeners. If the CDI listener runs first, then the container will no longer exist by the time the Concurrency one tries to terminate its executors. Since there's no priority system in ApplicationListeners, it may make sense to either make the `TransactionContextSetupParticipant` call the `ContainerUtil` "unchecked" method and only operate if the container still exists or modify that participant to be called during the container init/term lifecycle.

The trouble with the latter is that there's no guarantee that the CDI listener will _always_ be called before the Concurrency one. While that could be avoided by having CDI bootstrap the Concurrency support, there's no real guarantee that uses of Concurrency will happen after CDI container init.
