### ISSUE TITLE
Encountered "NotesException: Cannot create a session from an agent" in NSFSessionClonerSetupParticipant

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#371]
I saw this when using `invokeAll` on an injected `ManagedExecutorService`. It's possible that this could be worked around by doing the session cloning when the ClassLoader is swapped out.

```
java.lang.RuntimeException: NotesException: Cannot create a session from an agent
	at org.openntf.xsp.cdi.concurrency.NSFSessionClonerSetupParticipant.lambda$0(NSFSessionClonerSetupParticipant.java:75)
	at java.security.AccessController.doPrivileged(AccessController.java:691)
	at org.openntf.xsp.cdi.concurrency.NSFSessionClonerSetupParticipant.setup(NSFSessionClonerSetupParticipant.java:66)
	at org.openntf.xsp.jakarta.concurrency.DominoContextSetupProvider.lambda$2(DominoContextSetupProvider.java:63)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.openntf.xsp.jakarta.concurrency.DominoContextSetupProvider.setup(DominoContextSetupProvider.java:63)
	at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.setupContext(ManagedFutureTask.java:97)
	at org.glassfish.enterprise.concurrent.internal.ManagedThreadPoolExecutor.beforeExecute(ManagedThreadPoolExecutor.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:827)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:227)
	at org.openntf.xsp.jakarta.concurrency.NotesManagedThreadFactory$ManagedNotesThread.run(NotesManagedThreadFactory.java:76)
Caused by: NotesException: Cannot create a session from an agent
	at lotus.domino.local.Session.checkSecurityManagerExtender(Unknown Source)
	at lotus.domino.local.Session.createSession(Unknown Source)
	at lotus.domino.NotesFactory.createSession(Unknown Source)
	at org.openntf.xsp.cdi.concurrency.NSFSessionClonerSetupParticipant.lambda$0(NSFSessionClonerSetupParticipant.java:73)
	... 12 more
```

**Comment by jesse-gallagher** [comment]
Oddly, I _do_ changed the ClassLoader for the current thread, and even set the security manager to `null`. It's possible that this is a threading issue, where the swapping of the SecurityManager butts up against another thread setting it back.
