### ISSUE TITLE
Encountered disposed ClassLoader after altering NSF design

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#372]
I hit this when making a modification to an NSF's design and then hitting a JAX-RS endpoint that uses an injected `ManagedExecutorService`. I suspect that either it's not properly terminating/re-initializing the service or is somehow re-using the same ClassLoader.

```
java.lang.IllegalStateException: Invalid disposed application ClassLoader com.ibm.domino.xsp.module.nsf.ModuleClassLoader@8cf6c40c, for the application dev/jakarta.nsf.
     at com.ibm.domino.xsp.module.nsf.ModuleClassLoader.validateNotDisposed(ModuleClassLoader.java:244)
     at com.ibm.domino.xsp.module.nsf.ModuleClassLoader.getResource(ModuleClassLoader.java:210)
     at java.lang.ClassLoader.getResource(ClassLoader.java:598)
     at org.openntf.xsp.mvc.jaxrs.MvcJaxrsServiceParticipant$KrazoClassLoader.getResource(MvcJaxrsServiceParticipant.java:112)
     at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:721)
     at org.openntf.xsp.mvc.jaxrs.MvcJaxrsServiceParticipant$KrazoClassLoader.getResourceAsStream(MvcJaxrsServiceParticipant.java:125)
     at javax.faces.FactoryFinder.getImplNameFromServices(FactoryFinder.java:506)
     at javax.faces.FactoryFinder.getImplementationInstance(FactoryFinder.java:475)
     at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:276)
     at com.ibm.xsp.application.ApplicationEx._getInstance(ApplicationEx.java:96)
     at com.ibm.xsp.application.ApplicationEx.getInstance(ApplicationEx.java:75)
     at org.openntf.xsp.cdi.provider.ApplicationExCDIContainerLocator.getContainer(ApplicationExCDIContainerLocator.java:39)
     at org.openntf.xsp.cdi.provider.NSFCDIProvider.getCDI(NSFCDIProvider.java:53)
     at jakarta.enterprise.inject.spi.CDI.current(CDI.java:64)
     at org.openntf.xsp.jakarta.transaction.concurrency.TransactionContextSetupParticipant.reset(TransactionContextSetupParticipant.java:63)
     at org.openntf.xsp.jakarta.concurrency.DominoContextSetupProvider.lambda$3(DominoContextSetupProvider.java:72)
     at java.util.ArrayList.forEach(ArrayList.java:1259)
     at org.openntf.xsp.jakarta.concurrency.DominoContextSetupProvider.reset(DominoContextSetupProvider.java:72)
     at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:234)
     at org.openntf.xsp.jakarta.concurrency.NotesManagedThreadFactory$ManagedNotesThread.run(NotesManagedThreadFactory.java:76)
```

**Comment by jesse-gallagher** [comment]
I've been working with these extensively lately and haven't seen this trouble, so it was likely fixed as part of another change, or is so rare as to be nearly impossible to deduce.
