### ISSUE TITLE
Observed "Provider not found" when using NoSQL repository

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#373]
It looks like this is a static init not currently taken into account via the OSGi Weaving hook:

```
Caused by: jakarta.nosql.ProviderNotFoundException: Provider not found: interface jakarta.nosql.document.DocumentQueryParser
                at jakarta.nosql.ServiceLoaderProvider.lambda$load$1(ServiceLoaderProvider.java:139)
                at java.util.Optional.orElseThrow(Optional.java:290)
                at jakarta.nosql.ServiceLoaderProvider.load(ServiceLoaderProvider.java:139)
                at jakarta.nosql.ServiceLoaderProvider.getSupplier(ServiceLoaderProvider.java:43)
                at jakarta.nosql.ServiceLoaderProvider.get(ServiceLoaderProvider.java:59)
                at org.eclipse.jnosql.mapping.document.AbstractDocumentTemplate.<clinit>(AbstractDocumentTemplate.java:59)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:119)
                at org.jboss.weld.injection.ConstructorInjectionPoint.invokeAroundConstructCallbacks(ConstructorInjectionPoint.java:92)
                at org.jboss.weld.injection.ConstructorInjectionPoint.newInstance(ConstructorInjectionPoint.java:78)
                at org.jboss.weld.injection.producer.AbstractInstantiator.newInstance(AbstractInstantiator.java:28)
                at org.jboss.weld.injection.producer.BasicInjectionTarget.produce(BasicInjectionTarget.java:112)
                at org.jboss.weld.injection.producer.BeanInjectionTarget.produce(BeanInjectionTarget.java:186)
                at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:160)
... (21 lines left)
```

**Comment by jesse-gallagher** [comment]
I haven't seen this locally, but it makes sense how it'd happen. It's likely that it's dependent on the order of what you do on the server, and I've just lucked out.

**Comment by jesse-gallagher** [comment]
Looks like this can also show up with `Sorts#SortsProvider`.

**Comment by jesse-gallagher** [comment]
The trouble turned out to be the need to alter the Java policy - I had forgotten that this is how it manifests in NoSQL. I [modified the README](https://github.com/OpenNTF/org.openntf.xsp.jakartaee/commit/a87550f1f77209be2c222bec3e47c7f55bf8122e) to make an explicit note about this for the future.
