### ISSUE TITLE
Error in rest calls after adding class

### ISSUE THREAD

**Issue by tadrian** [OpenNTF/org.openntf.xsp.jakartaee#458]
I noticed if I add the following class to the examples.nsf the restapi stops working and retuns Error 500

```java
package com.consili;

import io.swagger.v3.oas.models.OpenAPI;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class Utils {
	
	private static String openApiToJsonString(OpenAPI openApi) {
	    try {
	        return new ObjectMapper().writeValueAsString(openApi);
	    } catch (JsonProcessingException e) {
	        throw new RuntimeException("Failed to serialize OpenAPI specification to JSON", e);
	    }
	}
}
```

```xml
<extendedDataElements name="CommonBaseEventLogRecord:Exception" type="string">
    <values>java.lang.NoClassDefFoundError: com.fasterxml.jackson.core.JsonProcessingException at sun.misc.Unsafe.ensureClassInitialized(Native Method) at java.lang.J9VMInternals.initialize(J9VMInternals.java:99) at java.lang.Class.forName(Class.java:426) at org.openntf.xsp.jakartaee.util.ModuleUtil.lambda$11(ModuleUtil.java:181) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1723) </values>
    <values>at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:497) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487) at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241) at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) at org.openntf.xsp.jakartaee.util.ModuleUtil.buildMatchingClasses(ModuleUtil.java:194) at org.openntf.xsp.jakartaee.AbstractXspLifecycleServlet.init(AbstractXspLifecycleServlet.java:104) at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.init(NewHttpServletWrapper.java:57) at com.ibm.designer.runtime.domino.adapter.ComponentModule.createServlet(ComponentModule.java:453) at org.openntf.xsp.jakarta.servlet.n</values>
    <values>sf.ServletServletFactory.lambda$0(ServletServletFactory.java:163) at java.util.HashMap.computeIfAbsent(HashMap.java:1128) at org.openntf.xsp.jakarta.servlet.nsf.ServletServletFactory.getExecutorServlet(ServletServletFactory.java:147) at org.openntf.xsp.jakarta.servlet.nsf.ServletServletFactory.getServletMatch(ServletServletFactory.java:67) at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:811) at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589) at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336) at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725) at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515) at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:76) </values>
    <values> at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:1) at com.mindoo.domino.jna.gc.NotesGC$1.run(NotesGC.java:596) at java.security.AccessController.doPrivileged(AccessController.java:691) at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:591) at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService.doService(DominoJNAHttpService.java:68) at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371) at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327) at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:302) Caused by: java.lang.ClassNotFoundException: Cannot find class com.fasterxml.jackson.core.JsonProcessingException in NSF at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:519) a</values>
    <values>t java.lang.ClassLoader.loadClassHelper(ClassLoader.java:957) at java.lang.ClassLoader.loadClass(ClassLoader.java:902) at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.loadClass(ModuleClassLoader.java:419) at java.lang.ClassLoader.loadClass(ClassLoader.java:885) ... 39 more Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException at java.net.URLClassLoader.findClass(URLClassLoader.java:591) at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:492) ... 43 more </values>
  </extendedDataElements>
```

**Comment by jesse-gallagher** [comment]
Hmm, did you deploy Jackson to the server? I could see this happening if you have Jackson in your local jvm/lib/ext in Designer but not on the server. The JEE project doesn't use it provide Jackson at all, so it won't come from there.

**Comment by perlausten** [comment]
What are you trying to accomplish, Thomas? You can get the OpenAPI result as JSON by using the `openapi.json` endpoint.

**Comment by jesse-gallagher** [comment]
That’s also true: you can likely get what you want with the MicroProfile OpenAPI feature from the project, and JSON-B is a good JSON library in lieu of Jackson for other needs.

**Comment by tadrian** [comment]
> What are you trying to accomplish, Thomas? You can get the OpenAPI result as JSON by using the `openapi.json` endpoint.

I was simply reporting a problem I had that caused the rest api to stop working.  I was not looking for a workaround.
