### ISSUE TITLE
java.lang.NoClassDefFoundError: org.primefaces.model.diagram.connector.Connector

### ISSUE THREAD

**Issue by slapraik-intec** [OpenNTF/org.openntf.xsp.jakartaee#459]
Tried putting the PrimeFaces jar into an XSP Library OSGi plugin (and adding it to an applications XSP properties) to see if this might help avoid the need to load stuff dynamically in the code.

It seems to work a little, but I get the following exception.

Encountered unhandled exception in Servlet
java.lang.NoClassDefFoundError: org.primefaces.model.diagram.connector.Connector
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
	at java.base/java.lang.J9VMInternals.initialize(J9VMInternals.java:163)
	at java.base/java.lang.Class.forName(Class.java:444)
	at org.openntf.xsp.jakartaee.util.ModuleUtil.lambda$11(ModuleUtil.java:181)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.openntf.xsp.jakartaee.util.ModuleUtil.buildMatchingClasses(ModuleUtil.java:194)
	at org.openntf.xsp.jsf.nsf.NSFJsfServlet.doInit(NSFJsfServlet.java:118)
	at org.openntf.xsp.jsf.nsf.NSFJsfServlet.lambda$0(NSFJsfServlet.java:147)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
	at org.openntf.xsp.jsf.nsf.NSFJsfServlet.service(NSFJsfServlet.java:142)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:112)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:302)
Caused by: java.lang.ClassNotFoundException: Cannot find class org.primefaces.model.diagram.connector.Connector in NSF
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:519)
	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1196)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1111)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.loadClass(ModuleClassLoader.java:419)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
	... 36 more
Caused by: java.lang.ClassNotFoundException: org.primefaces.model.diagram.connector.Connector
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:574)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:492)
	... 40 more

**Comment by slapraik-intec** [comment]
Hi.

Quick update on this.  

I was able to produce a similar issue without the OSGi Library, but instead by just adding the WebContent/WEB-INF/jakarta/lib/primefaces-12.0.0-jakarta.jar to the build path of the application database (except now the stacktrace reports line 100 of org.openntf.xsp.jakartaee.util.ModuleUtil whereas the first report was line 181). 

java.lang.NoClassDefFoundError: org.primefaces.model.diagram.connector.Connector
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1522)
	at java.base/java.lang.J9VMInternals.initialize(J9VMInternals.java:163)
	at java.base/java.lang.Class.forName(Class.java:444)
	at org.openntf.xsp.jakartaee.util.ModuleUtil.lambda$5(ModuleUtil.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:522)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.openntf.xsp.jakarta.servlet.nsf.ServletServletFactory.getModuleServlets(ServletServletFactory.java:178)
	at org.openntf.xsp.jakarta.servlet.nsf.ServletServletFactory.getServletMatch(ServletServletFactory.java:64)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:811)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:302)
Caused by: java.lang.ClassNotFoundException: Cannot find class org.primefaces.model.diagram.connector.Connector in NSF
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:519)
	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1196)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1111)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.loadClass(ModuleClassLoader.java:419)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
	... 27 more
Caused by: java.lang.ClassNotFoundException: org.primefaces.model.diagram.connector.Connector
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:574)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClass(ModuleClassLoader.java:492)
	... 31 more


I think the reason I did not discover this earlier was that I found I needed to click on the "Update the classpath settings" link on the [Overview] tab on the plugin.xml and restart the Domino HTTP task for the change in build path to be properly noticed.

Regards.

**Comment by slapraik-intec** [comment]
It was possible to workaround this issue by doing the following:

1. Create a custom version of the PrimeFaces JAR file
2. Edit the custom JAR and remove the "faces-config.xml" file
3. Add the custom JAR file into the Domino database (WebContent/WEB-INF/lib folder)
4. Add the custom JAR to the Domino database build path
5. Edit the plugin.xml file in the Domino database and on the Overview tab scroll down and click on "Update the classpath settings"
