### ISSUE TITLE
java.lang.IllegalStateException: context is already initialized

### ISSUE THREAD

**Issue by slapraik-intec** [OpenNTF/org.openntf.xsp.jakartaee#468]
Hi.

I sometimes get a "Encountered unhandled exception in Servlet - java.lang.IllegalStateException: context is already initialized" error when using JSF (and PrimeFaces but the error might be JSF related).

Encountered unhandled exception in Servlet
java.lang.IllegalStateException: context is already initialized
    at org.apache.myfaces.webapp.StartupServletContextListener.contextInitialized(StartupServletContextListener.java:85)
    at org.openntf.xsp.jsf.JsfServletContextListener.contextInitialized(JsfServletContextListener.java:37)
    at org.openntf.xsp.jakartaee.servlet.ServletUtil.lambda$1(ServletUtil.java:398)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
    at org.openntf.xsp.jakartaee.servlet.ServletUtil.contextInitialized(ServletUtil.java:398)
    at org.openntf.xsp.jsf.nsf.NSFJsfServlet.doInit(NSFJsfServlet.java:127)
    at org.openntf.xsp.jsf.nsf.NSFJsfServlet.lambda$0(NSFJsfServlet.java:147)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:748)
    at org.openntf.xsp.jsf.nsf.NSFJsfServlet.service(NSFJsfServlet.java:142)
    at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
    at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:112)

This was using OpenNTF Jakarta EE 2.13.0.202307211434 on a Domino 14 EA2 server.

**Comment by jesse-gallagher** [comment]
I haven't seen this locally, but I've additional check to try to guard against the same listener being added multiple times, which is a potential culprit.
