### ISSUE TITLE
JavaSapi service causes NPE in Verse requests when JavaSapi is enabled

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#476]
A bunch of Verse requests lead to this sort of stack trace on the console:

```
java.lang.NullPointerException: Cannot invoke "com.ibm.domino.xsp.module.nsf.NSFComponentModule.getModuleClassLoader()" because "mod" is null
     at org.openntf.xsp.jakartaee.bridge.jasapi.module.NSFComponentModuleJavaSapiService.withExtensions(NSFComponentModuleJavaSapiService.java:134)
     at org.openntf.xsp.jakartaee.bridge.jasapi.module.NSFComponentModuleJavaSapiService.endRequest(NSFComponentModuleJavaSapiService.java:71)
     at com.ibm.domino.bridge.http.jasapi.JavaSapiEnvironment.endRequest(JavaSapiEnvironment.java:813)
     at com.ibm.domino.bridge.http.jasapi.JavaSapiRequestExtension.endRequest(JavaSapiRequestExtension.java:159)
```

**Comment by jesse-gallagher** [comment]
I think the trouble is actually a knock-on effect of Verse trying to load my mail file when it doesn't exist on the server, which is why the module would be `null` there.
