### ISSUE TITLE
Observed "NotesContext not initiated for this thread" after making a JSP request and nothing else

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#48]
This showed up recently, and may be related to making use of `NSFService` but not actually initializing properly.

```
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.tell(XspCmdManager.java:92)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM: java.lang.IllegalStateException: NotesContext not initialized for the thread
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.domino.xsp.module.nsf.NotesContext.getCurrent(NotesContext.java:123)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClassesResource(ModuleClassLoa
der.java:570)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findApplicationResources(ModuleCla
ssLoader.java:629)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.domino.xsp.module.nsf.ModuleClassLoader.findApplicationResources(ModuleClassLoader.java:237)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.commons.extension.ExtensionManager$EclipseProvider.getResourcesList(ExtensionManager.java:380
)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.commons.extension.ExtensionManager$JavaServiceProvider.findInitializer(ExtensionManager.java:
267)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.commons.extension.ExtensionManager$EclipseProvider.findInitializer(ExtensionManager.java:368)

[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.commons.extension.ExtensionManager.loadServices(ExtensionManager.java:252)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.commons.extension.ExtensionManager.findApplicationServices(ExtensionManager.java:140)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.commons.extension.ExtensionManager.findApplicationServices(ExtensionManager.java:117)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.xsp.application.ApplicationEx.<init>(ApplicationEx.java:116)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.xsp.application.ApplicationExImpl.<init>(ApplicationExImpl.java:134)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.xsp.application.DesignerApplicationEx.<init>(DesignerApplicationEx.java:68)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.xsp.application.DesignerApplicationFactoryImpl.createApplicationInstance(DesignerApplicationF
actoryImpl.java:68)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.xsp.application.ApplicationFactoryImpl.createApplicationEx(ApplicationFactoryImpl.java:99)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.xsp.application.ApplicationFactoryImpl.getApplication(ApplicationFactoryImpl.java:70)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.xsp.application.ApplicationEx._getInstance(ApplicationEx.java:97)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.xsp.application.ApplicationEx.getInstance(ApplicationEx.java:75)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.xsp.application.ApplicationSessionListener.getApplication(ApplicationSessionListener.java:60)

[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.xsp.application.ApplicationSessionListener.sessionDestroyed(ApplicationSessionListener.java:4
8)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.ComponentModule.notifySessionRemoved(ComponentModule.java:382
)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.ComponentModule.checkSessionTimeout(ComponentModule.java:251)

[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.domino.xsp.module.nsf.NSFComponentModule.checkTimeout(NSFComponentModule.java:214)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.domino.xsp.module.nsf.NSFService.checkTimeout(NSFService.java:285)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.checkTimeout(LCDEnvironment.java:253)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.designer.runtime.domino.bootstrap.BootstrapEnvironment.tellCommand(BootstrapEnvironment.java:
388)
[0324:0002-174C] 12/18/2021 08:16:48 PM  HTTP JVM:      at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.tell(XspCmdManager.java:92)
```

**Comment by jesse-gallagher** [comment]
This seems to happen a bit over a minute after the request, so it easily could be related to the CDI application listener - my app is set to expire after a minute.

**Comment by jesse-gallagher** [comment]
This could also be due to CDI using a single-thread executor - Domino may re-use the thread.

**Comment by jesse-gallagher** [comment]
It doesn't _seem_ to be related to the CDI thread pool setting.

**Comment by jesse-gallagher** [comment]
Currently, this manifests as unsatisfied CDI dependencies, but the idea is the same: if you access a JSP page as your entrypoint to the NSF, it will fail, but doesn't fail if you first access an XPage or JAX-RS resource.
