### ISSUE TITLE
Investigate JSF

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#49]
In theory, with the right fiddling with fragments, it should be possible to use [Mojarra](https://eclipse-ee4j.github.io/mojarra/) to render .xhtml files.

It may also be preferable to make up an extension, such as .jsf, to support - .xhtml may be too broad, since it would apply to all DBs whether or not they opt in to the library.

**Comment by jesse-gallagher** [comment]
In the feature branch, I was able to get to a point where it hits this trouble on loading a page:

```
java.lang.NullPointerException
	at com.sun.faces.lifecycle.LifecycleImpl.(LifecycleImpl.java:77)
	at com.sun.faces.lifecycle.LifecycleFactoryImpl.(LifecycleFactoryImpl.java:55)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:2062)
	at jakarta.faces.FactoryFinderInstance.getImplGivenPreviousImpl(FactoryFinderInstance.java:431)
	at jakarta.faces.FactoryFinderInstance.getImplementationInstance(FactoryFinderInstance.java:330)
	at jakarta.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:183)
	at jakarta.faces.FactoryFinder.getFactory(FactoryFinder.java:264)
	at jakarta.faces.webapp.FacesServlet.acquireLifecycle(FacesServlet.java:494)
	at jakarta.faces.webapp.FacesServlet.init(FacesServlet.java:331)
	at org.openntf.xsp.jsf.nsf.NSFJsfServlet.init(NSFJsfServlet.java:72)
	at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.init(NewHttpServletWrapper.java:52)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.createServlet(ComponentModule.java:453)
	at org.openntf.xsp.jsf.nsf.JsfServletFactory.lambda$1(JsfServletFactory.java:111)
	at org.openntf.xsp.jsf.nsf.JsfServletFactory$$Lambda$4/0x0000000000000000.run(Unknown Source)
	at java.security.AccessController.doPrivileged(AccessController.java:738)
	at org.openntf.xsp.jsf.nsf.JsfServletFactory.getExecutorServlet(JsfServletFactory.java:92)
	at org.openntf.xsp.jsf.nsf.JsfServletFactory.getServletMatch(JsfServletFactory.java:80)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:811)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
```

Looking at the code, I'm not sure if I should be providing a different LifecycleFactory implementation (it seems like it expects multiple ones) or if there's another problem.

In general, it also looks like JSF very much expects Servlet 3+ aspects like annotation-based methods for entities and beans - it's unclear how much of that behavior is optional.

**Comment by jesse-gallagher** [comment]
As I left it for now, it hits this exception on request, after the init process:

```
java.lang.NullPointerException
     at jakarta.faces.CurrentThreadToServletContext.getFactoryFinder(CurrentThreadToServletContext.java:80)
     at jakarta.faces.CurrentThreadToServletContext.getFactoryFinder(CurrentThreadToServletContext.java:51)
     at jakarta.faces.FactoryFinder.getFactory(FactoryFinder.java:260)
     at com.sun.faces.context.FacesContextImpl.<init>(FacesContextImpl.java:104)
     at com.sun.faces.context.FacesContextFactoryImpl.getFacesContext(FacesContextFactoryImpl.java:69)
     at jakarta.faces.webapp.FacesServlet.acquireFacesContext(FacesServlet.java:522)
     at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:433)
     at org.openntf.xsp.jsf.nsf.NSFJsfServlet.lambda$0(NSFJsfServlet.java:157)
     at org.openntf.xsp.jsf.nsf.NSFJsfServlet$$Lambda$14/0x0000000000000000.run(Unknown Source)
     at java.security.AccessController.doPrivileged(AccessController.java:738)
     at org.openntf.xsp.jsf.nsf.NSFJsfServlet.service(NSFJsfServlet.java:139)
     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
     at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:65)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)
     at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
     at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
     at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
     at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
     at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)
     at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)
     at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
```

The NPE seems to come from a stored ClassLoader, but it might also be a FactoryFinder problem. Either way, it's possible that fixing this will require implementing other aspects of ConfigureListener - it also is set to listen on attribute changes of various kinds. Since the JSF servlet now stashes and restores XPages elements and this action could trigger a listener, there'll have to be some mechanism for removing or disabling listeners, which isn't available in `ServletContext` by default.
