### ISSUE TITLE
Cannot invoke "jakarta.faces.webapp.FacesServlet.destroy()" because "this.delegate" is null

### ISSUE THREAD

**Issue by slapraik-intec** [OpenNTF/org.openntf.xsp.jakartaee#537]
Domino 14 / Jakarta EE 3.0.0 / PrimeFaces 14.0.0.

Sometimes the following exception is being generated...

java.lang.NullPointerException: Cannot invoke "jakarta.faces.webapp.FacesServlet.destroy()" because "this.delegate" is null
    at org.openntf.xsp.jakarta.faces.nsf.NSFFacesServlet.destroy(NSFFacesServlet.java:225)
    at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.destroy(NewHttpServletWrapper.java:41)
    at org.openntf.xsp.jakartaee.MappingBasedServletFactory.getExecutorServlet(MappingBasedServletFactory.java:152)
    at org.openntf.xsp.jakartaee.MappingBasedServletFactory.getServletMatch(MappingBasedServletFactory.java:123)
    at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:811)
    at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
    at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
    at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
    at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
    at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)
    at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)
    at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:302)

**Comment by jesse-gallagher** [comment]
My best guess for what caused this is thread contention, which would be worth investigating specifically, but for now I added a null guard around the destroy() call to prevent this specific problem.
