### ISSUE TITLE
Observed exception when attempting to schedule a task in an `@Observes Startup` method

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#572]
```
org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type jakarta.enterprise.context.RequestScoped
     at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:654)
     at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:93)
     at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:169)
     at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:64)
     at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:86)
     at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:136)
     at org.openntf.xsp.jakarta.transaction.cdi.DominoTransactionProducer$Proxy$_$$_WeldClientProxy.peekTransaction(Unknown Source)
     at org.openntf.xsp.jakarta.transaction.concurrency.TransactionContextSetupParticipant.saveContext(TransactionContextSetupParticipant.java:44)
     at org.openntf.xsp.jakarta.concurrency.DominoContextSetupProvider.lambda$0(DominoContextSetupProvider.java:45)
     at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
     at org.openntf.xsp.jakarta.concurrency.DominoContextSetupProvider.saveContext(DominoContextSetupProvider.java:45)
     at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.captureContext(ManagedFutureTask.java:90)
     at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.<init>(ManagedFutureTask.java:60)
     at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor$TriggerControllerFuture.<init>(ManagedScheduledThreadPoolExecutor.java:611)
     at org.glassfish.enterprise.concurrent.internal.ManagedScheduledThreadPoolExecutor.schedule(ManagedScheduledThreadPoolExecutor.java:244)
     at org.glassfish.enterprise.concurrent.ManagedScheduledExecutorServiceImpl.schedule(ManagedScheduledExecutorServiceImpl.java:61)
     at org.openntf.xsp.jakarta.concurrency.jndi.DelegatingManagedScheduledExecutorService.schedule(DelegatingManagedScheduledExecutorService.java:136)
     at bean.SchedulerBean.onStartup(SchedulerBean.java:19)
     at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
     at java.base/java.lang.reflect.Method.invoke(Method.java:586)
     at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:99)
     at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
     at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:178)
     at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:342)
     at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:320)
     at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:298)
     at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:142)
     at org.jboss.weld.util.Observers.notify(Observers.java:176)
     at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:303)
     at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:289)
     at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
     at org.jboss.weld.environment.se.WeldContainer.fireContainerInitializedEvent(WeldContainer.java:247)
     at org.jboss.weld.environment.se.WeldContainer.endInitialization(WeldContainer.java:195)
     at org.jboss.weld.environment.se.Weld.initialize(Weld.java:858)
     at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.lambda$7(ContainerUtil.java:341)
     at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
     at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.lambda$6(ContainerUtil.java:318)
     at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.withLock(ContainerUtil.java:426)
     at org.openntf.xsp.jakarta.cdi.util.ContainerUtil.getContainer(ContainerUtil.java:275)
     at org.openntf.xsp.jakarta.cdi.impl.ContainerUtilProvider.getContainer(ContainerUtilProvider.java:33)
     at java.base/java.util.Optional.map(Optional.java:260)
     at org.openntf.xsp.jakarta.cdi.provider.ComponentModuleCDIContainerLocator.getContainer(ComponentModuleCDIContainerLocator.java:43)
     at org.openntf.xsp.jakarta.cdi.provider.DominoCDIProvider.getCDI(DominoCDIProvider.java:52)
     at jakarta.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:78)
     at jakarta.enterprise.inject.spi.CDI.current(CDI.java:65)
     at org.openntf.xsp.jakarta.rest.impl.JakartaRestServlet.initCdi(JakartaRestServlet.java:132)
     at org.openntf.xsp.jakarta.rest.impl.JakartaRestServlet.service(JakartaRestServlet.java:74)
     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
     at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:112)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:599)
     at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1359)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:886)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:829)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:588)
     at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1343)
     at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
     at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
     at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:371)
     at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:327)
     at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:302)
```

**Comment by jesse-gallagher** [comment]
I'm going to add a guard for this in the transaction handler, but the specific case of wanting to schedule tasks on startup remains a sticky problem.
