### ISSUE TITLE
Observed "NotesContext not initialized for the thread" in a managed thread

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#587]
This is happening in the `saveContext` method, so it may be something where we should guard to only call that on a non-managed thread, like we do somewhere else in the code base.

```
java.lang.IllegalStateException: NotesContext not initialized for the thread
	at com.ibm.domino.xsp.module.nsf.NotesContext.getCurrent(NotesContext.java:124)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findClassesResource(ModuleClassLoader.java:570)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader$DynamicClassLoader.findResource(ModuleClassLoader.java:544)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:749)
	at com.ibm.domino.xsp.module.nsf.ModuleClassLoader.getResource(ModuleClassLoader.java:211)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:746)
	at org.openntf.xsp.jakarta.mvc.rest.MvcRestServiceParticipant$KrazoClassLoader.getResource(MvcRestServiceParticipant.java:102)
	at java.base/java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:869)
	at org.openntf.xsp.jakarta.mvc.rest.MvcRestServiceParticipant$KrazoClassLoader.getResourceAsStream(MvcRestServiceParticipant.java:115)
	at javax.faces.FactoryFinder.getImplNameFromServices(FactoryFinder.java:506)
	at javax.faces.FactoryFinder.getImplementationInstance(FactoryFinder.java:475)
	at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:276)
	at com.ibm.xsp.application.ApplicationEx._getInstance(ApplicationEx.java:96)
	at com.ibm.xsp.application.ApplicationEx.getInstance(ApplicationEx.java:75)
	at org.openntf.xsp.jakartaee.discovery.impl.XPagesComponentEnabledLocator.isActive(XPagesComponentEnabledLocator.java:34)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:361)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:541)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:526)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:512)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:239)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
	at org.openntf.xsp.jakartaee.util.LibraryUtil.isLibraryActive(LibraryUtil.java:137)
	at org.openntf.xsp.jakarta.cdi.concurrency.CDIContextSetupParticipant.saveContext(CDIContextSetupParticipant.java:40)
	at org.openntf.xsp.jakarta.concurrency.DominoContextSetupProvider.lambda$0(DominoContextSetupProvider.java:45)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.openntf.xsp.jakarta.concurrency.DominoContextSetupProvider.saveContext(DominoContextSetupProvider.java:45)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl.newThread(ManagedThreadFactoryImpl.java:110)
	at org.openntf.xsp.jakarta.concurrency.NotesManagedThreadFactory.newThread(NotesManagedThreadFactory.java:62)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:637)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:928)
	at java.base/java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1021)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1158)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1595)
	at org.glassfish.enterprise.concurrent.ManagedThreadFactoryImpl$ManagedThread.run(ManagedThreadFactoryImpl.java:322)
	at org.openntf.xsp.jakarta.concurrency.NotesManagedThreadFactory$ManagedNotesThread.run(NotesManagedThreadFactory.java:77)
```

**Comment by jesse-gallagher** [comment]
This is a bit odd. The `isLibraryActive` call is actually unnecessary, so that can be removed, but this still should have been fine. The `NSFNotesContextParticipant` class should be run with higher priority and initializes NotesContext for the thread. Still, maybe just removing that call and relying on having set CDI by an earlier call in the pool for this thread would be fine.

**Comment by jesse-gallagher** [comment]
With the change I made to remove the unnecessary library check, I haven't seen this, so it's likely that either that fixed it or it's rare enough to not be a serious issue.
