### ISSUE TITLE
Bump Jakarta Data to 1.0.1 and JNoSQL to 1.1.3

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#594]
There seem to be some internal-only breaking changes, but the user API should be the same.

**Comment by jesse-gallagher** [comment]
Specifically, there's a bug in JNoSQL where a `JsonObject` entity property breaks loading with:

```
java.lang.ClassCastException: java.lang.Class incompatible with java.lang.reflect.ParameterizedType
	at org.eclipse.jnosql.mapping.reflection.DefaultMapFieldMetadata.&lt;init&gt;(DefaultMapFieldMetadata.java:41)
	at org.eclipse.jnosql.mapping.reflection.FieldMappingBuilder.buildMap(FieldMappingBuilder.java:115)
	at org.eclipse.jnosql.mapping.reflection.ReflectionClassConverter.to(ReflectionClassConverter.java:194)
```

The trouble here is that it sees it as a Map type (`MappingType.of` does `Map.class.isAssignableFrom(type)`) but then the constructor for `DefaultMapFieldMetadata` assumes that the type itself will be annotated. Instead, this should try to find the `Map` implementation and use that.
