### ISSUE TITLE
EL can't find compositeData in some cases where it'd be expected

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#6]
Hit in the `styleClass` property of a custom control:

```
<xp:table
	styleClass="filterTable table table-hover #{compositeData.tabController.viewTableAdditionalClasses}"
	id="viewTable">...</xp:table>
```

End of the stack trace:

```
Caused by: javax.el.PropertyNotFoundException: ELResolver cannot handle a null base Object with identifier 'compositeData'	at com.sun.el.lang.ELSupport.throwUnhandled(ELSupport.java:68)
	at com.sun.el.parser.AstIdentifier.getValue(AstIdentifier.java:126)
	at com.sun.el.parser.AstValue.getBase(AstValue.java:151)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:200)
	at com.sun.el.parser.AstDeferredExpression.getValue(AstDeferredExpression.java:63)
	at com.sun.el.parser.AstCompositeExpression.getValue(AstCompositeExpression.java:68)
	at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
	at org.openntf.xsp.el3.impl.ExpressionValueBinding.getValue(ExpressionValueBinding.java:52)
	at com.ibm.xsp.component.xp.XspTable.getStyleClass(XspTable.java:603)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at javax.faces.component.UIComponentBase$AttributesMap.get(UIComponentBase.java:1824)
	... 86 more
```

Other expressions work referencing `compositeData` on the same control, so I suspect that the problem is either to do with it being a mixed expression or something special about styleClass.

**Comment by jesse-gallagher** [comment]
It could also be related to the presence of an applicable theme property. These controls are added to the page using the Bazaar, which in turn applies styles on its own time. At that point, `compositeData` may not exist, and would usually resolve to "" in the core EL handler.

One level up in the stack trace includes:

```
Caused by: javax.faces.FacesException: javax.el.PropertyNotFoundException: ELResolver cannot handle a null base Object with identifier 'compositeData'
	at javax.faces.component.UIComponentBase$AttributesMap.get(UIComponentBase.java:1831)
	at com.ibm.xsp.stylekit.StyleKitImpl.applyProperties(StyleKitImpl.java:377)
	at com.ibm.xsp.stylekit.StyleKitImpl.applyStyle(StyleKitImpl.java:240)
	at com.ibm.xsp.stylekit.StyleKitImpl._applyStyles(StyleKitImpl.java:196)
	at com.ibm.xsp.stylekit.StyleKitImpl._applyStyles(StyleKitImpl.java:203)
	at com.ibm.xsp.stylekit.StyleKitImpl._applyStyles(StyleKitImpl.java:203)
	at com.ibm.xsp.stylekit.StyleKitImpl._applyStyles(StyleKitImpl.java:203)
	at com.ibm.xsp.stylekit.StyleKitImpl._applyStyles(StyleKitImpl.java:203)
	at com.ibm.xsp.stylekit.StyleKitImpl._applyStyles(StyleKitImpl.java:203)
	at com.ibm.xsp.stylekit.StyleKitImpl._applyStyles(StyleKitImpl.java:203)
	at com.ibm.xsp.stylekit.StyleKitImpl._applyStyles(StyleKitImpl.java:203)
	at com.ibm.xsp.stylekit.StyleKitImpl._applyStyles(StyleKitImpl.java:203)
	at com.ibm.xsp.stylekit.StyleKitImpl._applyStyles(StyleKitImpl.java:203)
	at com.ibm.xsp.stylekit.StyleKitImpl.applyStyles(StyleKitImpl.java:192)
	at com.ibm.xsp.extlib.builder.ControlBuilder.buildControl(ControlBuilder.java:52)
	at com.ibm.xsp.extlib.builder.ControlBuilder.buildControl(ControlBuilder.java:37)
	at **non-open-source client code**
	at javax.faces.component.UIComponent.invokeOnComponent(UIComponent.java:862)
	... 67 more
```

**Comment by jesse-gallagher** [comment]
In this case, I wonder what the best route is. I can see a couple options:

1. Change the implementation to behave similarly to the core: when there's a basic call to an empty object like this, just return "".
2. Add an option in xsp.properties to turn on this type of behavior per-app.
3. Add an implicit "compositeData" of an empty map to specially cover this kind of case, as it will be comparatively common.
4. Modify this app to work around the problem.

I'm wary of the first two, since having a stricter EL resolver is often beneficial - it's helped me find some errant typos and outdated bindings. The third option would be weird but defensible, and I may go with that.
