### ISSUE TITLE
Observed NPE in REST controller with MVC after a change

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#82]
The sequence of events was:

- Click around in the example app
- Load the MVC example properly
- Make a change to MvcExample to alter the model
- Visit the MVC example again

Unfortunately, the app then resumed working shortly thereafter - I'm not sure if it was after the one-minute app timeout currently set in there or if it's because I visited a different REST endpoint. Additionally, future changes to MvcExample didn't cause this trouble, so it appears to be intermittent.

```
com.ibm.xsp.FacesExceptionEx: java.lang.NullPointerException
     at com.ibm.xsp.context.FacesContextExImpl.<init>(FacesContextExImpl.java:317)
     at com.ibm.xsp.domino.context.DominoFacesContext.<init>(DominoFacesContext.java:32)
     at com.ibm.xsp.domino.context.DominoFacesContextFactoryImpl.getFacesContext(DominoFacesContextFactoryImpl.java:67)
     at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.initContext(FacesJAXRSServletContainer.java:157

     at org.openntf.xsp.jaxrs.impl.FacesJAXRSServletContainer.service(FacesJAXRSServletContainer.java:105)
     at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
     at org.openntf.xsp.jakartaee.servlet.NewHttpServletWrapper.service(NewHttpServletWrapper.java:65)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule.invokeServlet(ComponentModule.java:600)
     at com.ibm.domino.xsp.module.nsf.NSFComponentModule.invokeServlet(NSFComponentModule.java:1352)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule$AdapterInvoker.invokeServlet(ComponentModule.java:877)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule$ServletInvoker.doService(ComponentModule.java:820)
     at com.ibm.designer.runtime.domino.adapter.ComponentModule.doService(ComponentModule.java:589)
     at com.ibm.domino.xsp.module.nsf.NSFComponentModule.doService(NSFComponentModule.java:1336)
     at com.ibm.domino.xsp.module.nsf.NSFService.doServiceInternal(NSFService.java:725)
     at com.ibm.domino.xsp.module.nsf.NSFService.doService(NSFService.java:515)
     at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.doService(LCDEnvironment.java:363)
     at com.ibm.designer.runtime.domino.adapter.LCDEnvironment.service(LCDEnvironment.java:319)
     at com.ibm.domino.xsp.bridge.http.engine.XspCmdManager.service(XspCmdManager.java:272)
Caused by:
java.lang.NullPointerException
     at com.sun.faces.context.FacesContextImpl.getApplication(FacesContextImpl.java:154)
     at com.ibm.xsp.context.FacesContextExImpl.<init>(FacesContextExImpl.java:219)
     ... 17 more
```

**Comment by jesse-gallagher** [comment]
This hasn't been reproducible in a while, and the way the JAX-RS init process works has changed noticeably. It's possible this is still creeping around, but for now it's likely safe to consider it fixed as a side effect of other changes.
