### ISSUE TITLE
Improve handling of exceptions in MVC

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/org.openntf.xsp.jakartaee#94]
Currently, an exception that arises during MVC processing results in this:

```
Caused by:
jakarta.ws.rs.ServerErrorException: Unable to find suitable view engine for 'org.openntf.xsp.jsonapi.jaxrs.exceptions.GenericThrowableMapper$$Lambda$249/0x0000000000000000@2d71d672'
     at org.eclipse.krazo.core.ViewableWriter.writeTo(ViewableWriter.java:129)
     at org.eclipse.krazo.core.ViewableWriter.writeTo(ViewableWriter.java:71)
     at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$writeTo$1(ServerWriterInterceptorContext.java:79)
     at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext$$Lambda$319/0x0000000000000000.run(Unknown Source)
     at org.jboss.resteasy.core.SynchronousExecutionContext.executeBlockingIo(SynchronousExecutionContext.java:235)
     at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:79)
     at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:245)
     at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:170)
     at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:73)
     at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext$$Lambda$315/0x0000000000000000.get(Unknown Source)
     at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:93)
     at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:73)
     at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:163)
     at org.jboss.resteasy.core.ServerResponseWriter$$Lambda$314/0x0000000000000000.run(Unknown Source)
     at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
     at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
     at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
     at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
     at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:226)
     ... 25 more
```

**Comment by jesse-gallagher** [comment]
In my blog, I handled this by having the mapper look for MVC requests and handle those by returning a `Viewable`:

https://github.com/jesse-gallagher/frostillic.us-Blog/blob/develop/frostillicus-blog/frostillicus-blog-j2ee/src/main/java/jaxrs/GenericExceptionHandler.java
